# frozen_string_literal: true

module Mindee
  module Product
    module BillOfLading
      class BillOfLadingV1CarrierItems < Array[untyped]
        def initialize: (Array[untyped], Integer?) -> void
        def self.line_items_separator: (String) -> String
        def to_s: -> String
      end
    end
  end
end
