# lib/mindee/product/bill_of_lading/bill_of_lading_v1_carrier.rb
module Mindee
  module Product
    module BillOfLading
      class BillOfLadingV1Carrier # failed to identify its superclass
        def name: -> untyped
        def professional_number: -> untyped
        def scac: -> untyped
        def initialize: (untyped, untyped) -> untyped
        def printable_values: -> Hash[untyped, untyped]
        def to_s: -> String
      end
    end
  end
end
