# lib/mindee/product/bill_of_lading/bill_of_lading_v1_document.rb
module Mindee
  module Product
    module BillOfLading
      class BillOfLadingV1Document # failed to identify its superclass
        def bill_of_lading_number: -> untyped
        def carrier: -> untyped
        def carrier_items: -> []
        def consignee: -> untyped
        def date_of_issue: -> untyped
        def departure_date: -> untyped
        def notify_party: -> untyped
        def place_of_delivery: -> untyped
        def port_of_discharge: -> untyped
        def port_of_loading: -> untyped
        def shipper: -> untyped
        def initialize: (untyped, untyped) -> untyped
        def to_s: -> String
        def carrier_items_separator: (String) -> String
        def carrier_items_to_s: -> String
      end
    end
  end
end
