# TypeProf 0.30.1

# lib/mindee/product/bill_of_lading/bill_of_lading_v1_page.rb
module Mindee
  module Product
    module Product::BillOfLading
      class Product::BillOfLading::BillOfLadingV1Page # failed to identify its superclass
        def initialize: (untyped) -> nil
      end
      class Product::BillOfLading::BillOfLadingV1PagePrediction # failed to identify its superclass
        def to_s: -> String
      end
    end
  end
end
