# lib/mindee/product/bill_of_lading/bill_of_lading_v1_page.rb
module Mindee
  module Product
    module BillOfLading
      class BillOfLadingV1Page # failed to identify its superclass
        def initialize: (untyped) -> nil
      end
      class BillOfLadingV1PagePrediction # failed to identify its superclass
        def to_s: -> String
      end
    end
  end
end
