# TypeProf 0.30.1

# lib/mindee/product/bill_of_lading/bill_of_lading_v1_notify_party.rb
module Mindee
  module Product
    module Product::BillOfLading
      class Product::BillOfLading::BillOfLadingV1NotifyParty # failed to identify its superclass
        def address: -> untyped
        def email: -> untyped
        def name: -> untyped
        def phone: -> untyped
        def initialize: (untyped, untyped) -> untyped
        def printable_values: -> Hash[untyped, untyped]
        def to_s: -> String
      end
    end
  end
end
