module Mindee
  module Product
    module BillOfLading
      class BillOfLadingV1NotifyParty < Parsing::Standard::FeatureField
        def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
        def address: -> String
        def email: -> String
        def name: -> String
        def phone: -> String
        def printable_values: -> Hash[String | Symbol, untyped]
        def to_s: -> String
      end
    end
  end
end
