# lib/mindee/product/bill_of_lading/bill_of_lading_v1_page.rb

module Mindee
  module Product
    module BillOfLading
      class BillOfLadingV1Page < Parsing::Common::Page
        def initialize: (Hash[Symbol | String, untyped]) -> void
      end
      class BillOfLadingV1PagePrediction < BillOfLadingV1Document
        def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
        def to_s: -> String
      end
    end
  end
end
