# lib/mindee/product/fr/health_card/health_card_v1_page.rb
module Mindee
  module Product
    module FR
      module HealthCard
        class HealthCardV1Page # failed to identify its superclass
          def initialize: (untyped) -> nil
        end
        class HealthCardV1PagePrediction # failed to identify its superclass
          def to_s: -> String
        end
      end
    end
  end
end
