# TypeProf 0.30.1

# lib/mindee/product/fr/health_card/health_card_v1.rb
module Mindee
  module Product
    module Product::FR
      module Product::FR::HealthCard
        class Product::FR::HealthCard::HealthCardV1 # failed to identify its superclass
          def initialize: (untyped) -> untyped
          def endpoint_name: -> untyped
          def endpoint_version: -> untyped
          def has_async: -> untyped
          def has_sync: -> untyped
        end
      end
    end
  end
end
