# lib/mindee/product/invoice/invoice_v4_page.rb
module Mindee
  module Product
    module Invoice
      class InvoiceV4Page # failed to identify its superclass
        def initialize: (untyped) -> nil
      end
      class InvoiceV4PagePrediction # failed to identify its superclass
        def to_s: -> String
      end
    end
  end
end
