# lib/mindee/product/invoice/invoice_v4_page.rb

module Mindee
  module Product
    module Invoice
      class InvoiceV4Page < Parsing::Common::Page
        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
      class InvoiceV4PagePrediction < InvoiceV4Document
        def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
        def to_s: -> String
      end
    end
  end
end
