# lib/mindee/image/extracted_image.rb
module Mindee
  module Image
    class ExtractedImage
      def logger: () -> Logger
      def page_id: -> Integer
      def element_id: -> Integer
      def buffer: -> StringIO
      def filename: -> String
      def initialize: (
        Input::Source::LocalInputSource | Input::Source::BytesInputSource,
        Integer,
        Integer?,
        ?preserve_input_filename: bool
      ) -> Integer
      def write_to_file: (String, ?String?) -> void
      def as_source: -> Input::Source::BytesInputSource
      def as_input_source: -> Input::Source::BytesInputSource
    end
  end
end
