# lib/mindee/image/image_extractor.rb
module Mindee
  module Image
    module ImageExtractor
      def self.attach_image_as_new_file: (StringIO, ?format: String) -> Origami::PDF
      def self.to_blob: () -> String
      def self.extract_multiple_images_from_source: (Input::Source::LocalInputSource, Integer, Array[Array[Geometry::Point] | Array[Geometry::Quadrilateral]]) -> Array[ExtractedImage]
      def self.extract_images_from_polygons: (Input::Source::LocalInputSource, StringIO, Integer, Array[Geometry::Point] | Geometry::Quadrilateral) -> Array[ExtractedImage]
      def self.create_extracted_image: (StringIO, String, Integer, Integer) -> void
      def self.load_input_source_pdf_page_as_stringio: (Input::Source::LocalInputSource, Integer) -> StringIO
    end
  end
end
