# lib/mindee/image/image_compressor.rb
module Mindee
  module Image
    module ImageCompressor
      def self.compress_image: (untyped, ?quality: Integer, ?max_width: nil, ?max_height: nil) -> untyped
    end
  end
end
