# lib/mindee/image/image_compressor.rb
module Mindee
  module Image
    module ImageCompressor
      def self.compress_image: (MiniMagick::Image | StringIO | File, ?quality: Integer | Float?, ?max_width: Integer | Float?, ?max_height: Integer | Float?) -> StringIO
    end
  end
end
