# lib/mindee/product/fr/carte_grise/carte_grise_v1_page.rb
module Mindee
  module Product
    module FR
      module CarteGrise
        class CarteGriseV1Page # failed to identify its superclass
          def initialize: (untyped) -> nil
        end
        class CarteGriseV1PagePrediction # failed to identify its superclass
          def to_s: -> String
        end
      end
    end
  end
end
