# lib/mindee/product/fr/carte_grise/carte_grise_v1_document.rb
module Mindee
  module Product
    module FR
      module CarteGrise
        class CarteGriseV1Document # failed to identify its superclass
          def a: -> untyped
          def b: -> untyped
          def c1: -> untyped
          def c3: -> untyped
          def c41: -> untyped
          def c4a: -> untyped
          def d1: -> untyped
          def d3: -> untyped
          def e: -> untyped
          def f1: -> untyped
          def f2: -> untyped
          def f3: -> untyped
          def formula_number: -> untyped
          def g: -> untyped
          def g1: -> untyped
          def i: -> untyped
          def j: -> untyped
          def j1: -> untyped
          def j2: -> untyped
          def j3: -> untyped
          def mrz1: -> untyped
          def mrz2: -> untyped
          def owner_first_name: -> untyped
          def owner_surname: -> untyped
          def p1: -> untyped
          def p2: -> untyped
          def p3: -> untyped
          def p6: -> untyped
          def q: -> untyped
          def s1: -> untyped
          def s2: -> untyped
          def u1: -> untyped
          def u2: -> untyped
          def v7: -> untyped
          def x1: -> untyped
          def y1: -> untyped
          def y2: -> untyped
          def y3: -> untyped
          def y4: -> untyped
          def y5: -> untyped
          def y6: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def to_s: -> String
        end
      end
    end
  end
end
