# lib/mindee/product/../carte_grise/carte_grise_v1.rb

module Mindee
  module Product
    module FR
      module CarteGrise
        class CarteGriseV1 < Parsing::Common::Inference
          def initialize: (Hash[Symbol | String, untyped]) -> void
        end
      end
    end
  end
end
