# lib/mindee/product/../carte_grise/carte_grise_v1_page.rb

module Mindee
  module Product
    module FR
      module CarteGrise
        class CarteGriseV1Page < Parsing::Common::Page
          def initialize: (Hash[String | Symbol, untyped]) -> void
        end
        class CarteGriseV1PagePrediction < CarteGriseV1Document
          def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
          def to_s: -> String
        end
      end
    end
  end
end
