# lib/mindee/product/universal/universal_page.rb
module Mindee
  module Product
    module Universal
      class UniversalPage # failed to identify its superclass
        def initialize: (untyped) -> untyped
      end
      class UniversalPagePrediction # failed to identify its superclass
        def initialize: (untyped, ?nil) -> untyped
        def to_s: -> String
      end
    end
  end
end
