# lib/mindee/product/universal/universal.rb
module Mindee
  module Product
    module Universal
      class Universal < Parsing::Common::Inference
        def initialize: (Hash[String | Symbol, untyped]) -> void
        def endpoint_name: -> String
        def endpoint_version: -> String
        def has_async: -> bool
        def has_sync: -> bool
      end
    end
  end
end
