# TypeProf 0.30.1

# lib/mindee/product/universal/universal_page.rb
module Mindee
  module Product
    module Product::Universal
      class Product::Universal::UniversalPage # failed to identify its superclass
        def initialize: (untyped) -> untyped
      end
      class Product::Universal::UniversalPagePrediction # failed to identify its superclass
        def initialize: (untyped, ?nil) -> untyped
        def to_s: -> String
      end
    end
  end
end
