AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - _test.rb

  TargetRubyVersion: 2.6
  SuggestExtensions: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'

Metrics/MethodLength:
  Max: 45

Metrics/ClassLength:
  Max: 200

Metrics/ParameterLists:
  Max: 7

Metrics/AbcSize:
  Max: 60

Style/RegexpLiteral:
  EnforcedStyle: percent_r
