# lib/mindee/client_v2.rb

OTS_OWNER: String
module Mindee
  class ClientV2
    private attr_reader mindee_api: HTTP::MindeeApiV2

    def logger: () -> Logger
    def initialize: (?api_key: String) -> void
    def get_result: [T] (HTTP::_ProductClass[T] product, String resource) -> T
    def get_job: (String job_id) -> V2::Parsing::JobResponse
    def enqueue: [T] (HTTP::_ProductClass[T] product, Input::Source::LocalInputSource | Input::Source::URLInputSource, Hash[String | Symbol, untyped] | Input::BaseParameters params) -> V2::Parsing::JobResponse
    def enqueue_and_get_result: [T] (HTTP::_ProductClass[T] product, Input::Source::LocalInputSource | Input::Source::URLInputSource, Hash[String | Symbol, untyped] | Input::BaseParameters params) -> T
    def validate_async_params:  (Integer | Float, Integer | Float, Integer) -> void
    def normalize_parameters: (singleton(Input::BaseParameters) param_class, Hash[String | Symbol, untyped] | Input::BaseParameters params) -> Input::BaseParameters
  end
end
