# lib/mindee/client_v2.rb

OTS_OWNER: String
module Mindee
  interface _ParametersFactory[T]
    def from_hash: (params: untyped) -> T
  end
  class ClientV2
    attr_reader mindee_api: HTTP::MindeeApiV2

    def logger: () -> Logger
    def initialize: (?api_key: String) -> void
    def get_inference: (String) -> Mindee::Parsing::V2::InferenceResponse
    def get_result: [T] (HTTP::_ResponseFactory[T] response_class, String inference_id) -> T
    def get_result_url: [T] (HTTP::_ResponseFactory[T] response_class, String inference_id) -> T
    def get_job: (String) -> Mindee::Parsing::V2::JobResponse
    def enqueue_inference: (Input::Source::LocalInputSource | Input::Source::URLInputSource, Hash[String | Symbol, untyped] | Input::InferenceParameters, disable_redundant_warnings: bool) -> Mindee::Parsing::V2::JobResponse
    def enqueue: (Input::Source::LocalInputSource | Input::Source::URLInputSource, Input::BaseParameters) -> Mindee::Parsing::V2::JobResponse
    def enqueue_and_get_result: [T < Input::BaseParameters] (
        singleton(Mindee::V2::Parsing::BaseResponse),
          Input::Source::LocalInputSource | Input::Source::URLInputSource,
          Hash[String | Symbol, untyped] | T
      ) -> Mindee::V2::Parsing::BaseResponse[untyped]
    def enqueue_and_get_inference: (Input::Source::LocalInputSource | Input::Source::URLInputSource, Hash[String | Symbol, untyped] | Input::InferenceParameters) -> Mindee::Parsing::V2::InferenceResponse
    def validate_async_params:  (Integer | Float, Integer | Float, Integer) -> void
    def normalize_parameters: [T < Input::BaseParameters] (_ParametersFactory[T], Hash[String | Symbol, untyped] | T) -> T
  end
end
