# lib/mindee/version.rb
module Mindee
  VERSION: String
  def self.find_platform: -> (:bsd | :linux | :macos | :solaris | :windows | Hash[Symbol | String, Regexp])?
  PLATFORM: (Hash[Symbol | String, Regexp] | Symbol)
end
