# lib/mindee/product/financial_document/financial_document_v1_page.rb
module Mindee
  module Product
    module FinancialDocument
      class FinancialDocumentV1Page # failed to identify its superclass
        def initialize: (untyped) -> nil
      end
      class FinancialDocumentV1PagePrediction # failed to identify its superclass
        def to_s: -> String
      end
    end
  end
end
