# lib/mindee/product/financial_document/financial_document_v1_page.rb

module Mindee
  module Product
    module FinancialDocument
      class FinancialDocumentV1Page < Parsing::Common::Page
        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
      class FinancialDocumentV1PagePrediction < FinancialDocumentV1Document
        def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
        def to_s: -> String
      end
    end
  end
end
