# lib/mindee/product/financial_document/financial_document_v1.rb

module Mindee
  module Product
    module FinancialDocument
      class FinancialDocumentV1 < Parsing::Common::Inference
        def initialize: (Hash[Symbol | String, untyped]) -> void
      end
    end
  end
end
