# lib/mindee/product/financial_document/financial_document_v1_document.rb
module Mindee
  module Product
    module FinancialDocument
      class FinancialDocumentV1Document # failed to identify its superclass
        def billing_address: -> untyped
        def category: -> untyped
        def customer_address: -> untyped
        def customer_company_registrations: -> []
        def customer_id: -> untyped
        def customer_name: -> untyped
        def date: -> untyped
        def document_number: -> untyped
        def document_type: -> untyped
        def due_date: -> untyped
        def invoice_number: -> untyped
        def line_items: -> []
        def locale: -> untyped
        def payment_date: -> untyped
        def po_number: -> untyped
        def receipt_number: -> untyped
        def reference_numbers: -> []
        def shipping_address: -> untyped
        def subcategory: -> untyped
        def supplier_address: -> untyped
        def supplier_company_registrations: -> []
        def supplier_email: -> untyped
        def supplier_name: -> untyped
        def supplier_payment_details: -> []
        def supplier_phone_number: -> untyped
        def supplier_website: -> untyped
        def taxes: -> untyped
        def time: -> untyped
        def tip: -> untyped
        def total_amount: -> untyped
        def total_net: -> untyped
        def total_tax: -> untyped
        def initialize: (untyped, untyped) -> untyped
        def to_s: -> String
        def line_items_separator: (String) -> String
        def line_items_to_s: -> String
      end
    end
  end
end
