# lib/mindee/parsing/common/api_request.rb
module Mindee
  module Parsing
    module Common
      class ApiRequest
        def error: -> Hash[String, untyped]
        def ressources: -> Array[String]
        def status: -> [RequestStatus, Symbol]
        def status_code: -> Integer
        def url: -> String
        def initialize: (Hash[String, untyped]) -> void
      end
    end
  end
end
