# TypeProf 0.30.1

# lib/mindee/parsing/common/document.rb
module Mindee
  module Parsing
    module Parsing::Common
      class Parsing::Common::Document
        def inference: -> untyped
        def name: -> untyped
        def id: -> untyped
        def extras: -> nil
        def ocr: -> nil
        def n_pages: -> untyped
        def self.load_ocr: (untyped) -> nil
        def self.extract_extras: (untyped) -> nil
        def initialize: (untyped, untyped) -> untyped
        def to_s: -> String
        def inject_full_text_ocr: (untyped) -> nil
      end
    end
  end
end
