# lib/mindee/parsing/common/document.rb
module Mindee
  module Parsing
    module Common
      class Document
        def inference: -> untyped
        def name: -> untyped
        def id: -> untyped
        def extras: -> nil
        def ocr: -> nil
        def n_pages: -> untyped
        def self.load_ocr: (untyped) -> Parsing::Common::OCR::OCR?
        def self.extract_extras: (untyped) -> Parsing::Common::Extras::Extras?
        def initialize: (untyped, untyped) -> untyped
        def to_s: -> String
        def inject_full_text_ocr: (untyped) -> untyped
      end
    end
  end
end
