# lib/mindee/parsing/common/document.rb
module Mindee
  module Parsing
    module Common
      class Document
        def inference: -> Inference
        def name: -> String
        def id: -> String
        def extras: -> Extras::Extras?
        def ocr: -> OCR::OCR?
        def n_pages: -> Integer
        def self.load_ocr: (Hash[String | Symbol, untyped]) -> Parsing::Common::OCR::OCR?
        def self.extract_extras: (Hash[String | Symbol, untyped]) -> Parsing::Common::Extras::Extras?
        def initialize: (singleton(Parsing::Common::Inference), Hash[String | Symbol, untyped]) -> void
        def to_s: -> String
        def inject_full_text_ocr: (Hash[String | Symbol, untyped]) -> void
      end
    end
  end
end
