# lib/mindee/parsing/common/execution_file.rb
module Mindee
  module Parsing
    module Common
      class ExecutionFile
        def name: -> String
        def alias: -> String?
        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
    end
  end
end
