# TypeProf 0.30.1

# lib/mindee/parsing/common/execution_file.rb
module Mindee
  module Parsing
    module Parsing::Common
      class Parsing::Common::ExecutionFile
        def name: -> untyped
        def alias: -> untyped
        def initialize: (untyped) -> untyped
      end
    end
  end
end
