# lib/mindee/parsing/common/inference.rb
module Mindee
  module Parsing
    module Common
      class Inference
        def is_rotation_applied: -> untyped
        def pages: -> Array[Page]
        def prediction: -> untyped
        def product: -> untyped
        def initialize: (untyped) -> void
        def to_s: -> String
        def self.endpoint_name: -> String
        def self.endpoint_version: -> String
        def self.has_async: -> bool
        def self.has_sync: -> bool
      end
    end
  end
end
