# lib/mindee/parsing/common/page.rb
module Mindee
  module Parsing
    module Common
      class Page
        attr_reader extras: Extras::Extras
        attr_reader orientation: Common::Orientation
        attr_reader page_id: Integer
        attr_reader prediction: Common::Prediction

        def initialize: (Hash[String | Symbol, untyped]) -> void
        def to_s: -> String
      end
    end
  end
end
