# TypeProf 0.30.1

# lib/mindee/parsing/common/product.rb
module Mindee
  module Parsing
    module Parsing::Common
      class Parsing::Common::Product
        def name: -> untyped
        def type: -> untyped
        def version: -> untyped
        def initialize: (untyped) -> untyped
      end
    end
  end
end
