# lib/mindee/parsing/common/workflow_response.rb
module Mindee
  module Parsing
    module Common
      class WorkflowResponse
        @api_request: ApiRequest
        @execution: Execution
        @raw_http: String

        def execution: -> Execution
        def api_request: -> ApiRequest
        def raw_http: -> String
        def initialize: (singleton(Parsing::Common::Inference), Hash[String | Symbol, untyped] | Net::HTTPResponse, String) -> void
      end
    end
  end
end
