# lib/mindee/parsing/common/workflow_response.rb
module Mindee
  module Parsing
    module Common
      class WorkflowResponse
        def execution: -> untyped
        def api_request: -> untyped
        def raw_http: -> untyped
        def initialize: (untyped, untyped, untyped) -> untyped
      end
    end
  end
end
