module Mindee
  module V2
    module Product
      module Crop
        class CropItem
          attr_reader object_type: String
          attr_reader location: Mindee::Parsing::V2::Field::FieldLocation

          def initialize: (Hash[String | Symbol, untyped]) -> void
          def to_s: -> String
        end
      end
    end
  end
end
