module Mindee
  module V2
    module Product
      module Crop
        class CropItem
          attr_reader object_type: String
          attr_reader location: Mindee::V2::Parsing::Field::FieldLocation

          def initialize: (Hash[String | Symbol, untyped]) -> void

          def extract_from_file: (Input::Source::LocalInputSource) -> Image::ExtractedImage

          def to_s: -> String
        end
      end
    end
  end
end
