# lib/mindee/product/fr/payslip/payslip_v3_employee.rb
module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV3Employee # failed to identify its superclass
          def address: -> untyped
          def date_of_birth: -> untyped
          def first_name: -> untyped
          def last_name: -> untyped
          def phone_number: -> untyped
          def registration_number: -> untyped
          def social_security_number: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, untyped]
          def to_s: -> String
        end
      end
    end
  end
end
