# lib/mindee/product/fr/payslip/payslip_v3_paid_time_off.rb
module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV3PaidTimeOff # failed to identify its superclass
          def accrued: -> untyped
          def period: -> untyped
          def pto_type: -> untyped
          def remaining: -> untyped
          def used: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, String]
          def table_printable_values: -> Hash[untyped, String]
          def to_table_line: -> String
          def to_s: -> String
        end
      end
    end
  end
end
