module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV3SalaryDetail < Parsing::Standard::FeatureField
          def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
          def amount: -> Float
          def base: -> Float
          def description: -> String
          def number: -> Float
          def rate: -> Float
          def printable_values: -> Hash[Symbol | String, untyped]
          def table_printable_values: -> Hash[Symbol | String, untyped]
          def to_table_line: -> String
          def to_s: -> String
        end
      end
    end
  end
end
