module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV3Employment < Parsing::Standard::FeatureField
          def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
          def category: -> String
          def coefficient: -> String
          def collective_agreement: -> String
          def job_title: -> String
          def position_level: -> String
          def seniority_date: -> String
          def start_date: -> String
          def printable_values: -> Hash[String | Symbol, untyped]
          def to_s: -> String
        end
      end
    end
  end
end
