# lib/mindee/product/fr/payslip/payslip_v3_pay_period.rb
module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV3PayPeriod # failed to identify its superclass
          def end_date: -> untyped
          def month: -> untyped
          def payment_date: -> untyped
          def start_date: -> untyped
          def year: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, untyped]
          def to_s: -> String
        end
      end
    end
  end
end
