# frozen_string_literal: true

module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV2SalaryDetails < Array[untyped]
          def initialize: (Array[untyped], Integer?) -> void
          def self.line_items_separator: (char) -> String
          def to_s: -> String
        end
      end
    end
  end
end
