module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV2BankAccountDetail < Parsing::Standard::FeatureField
          def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
          def bank_name: -> String
          def iban: -> String
          def swift: -> String
          def printable_values: -> Hash[Symbol | String, untyped]
          def to_s: -> String
        end
      end
    end
  end
end
