# TypeProf 0.30.1

# lib/mindee/product/fr/payslip/payslip_v2_employee.rb
module Mindee
  module Product
    module Product::FR
      module Product::FR::Payslip
        class Product::FR::Payslip::PayslipV2Employee # failed to identify its superclass
          def address: -> untyped
          def date_of_birth: -> untyped
          def first_name: -> untyped
          def last_name: -> untyped
          def phone_number: -> untyped
          def registration_number: -> untyped
          def social_security_number: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, untyped]
          def to_s: -> String
        end
      end
    end
  end
end
