# lib/mindee/product/../payslip/payslip_v2_page.rb

module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV2Page < Parsing::Common::Page
          def initialize: (Hash[String | Symbol, untyped]) -> void
        end
        class PayslipV2PagePrediction < PayslipV2Document
          def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
          def to_s: -> String
        end
      end
    end
  end
end
