# lib/mindee/product/fr/payslip/payslip_v3_salary_detail.rb
module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV3SalaryDetail # failed to identify its superclass
          def amount: -> untyped
          def base: -> untyped
          def description: -> untyped
          def number: -> untyped
          def rate: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, String]
          def table_printable_values: -> Hash[untyped, String]
          def to_table_line: -> String
          def to_s: -> String
        end
      end
    end
  end
end
