module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV3Employer < Parsing::Standard::FeatureField
          def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
          def address: -> String
          def company_id: -> String
          def company_site: -> String
          def naf_code: -> String
          def name: -> String
          def phone_number: -> String
          def urssaf_number: -> String
          def printable_values: -> Hash[String | Symbol, untyped]
          def to_s: -> String
        end
      end
    end
  end
end
