# lib/mindee/product/fr/payslip/payslip_v3_page.rb
module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV3Page # failed to identify its superclass
          def initialize: (untyped) -> nil
        end
        class PayslipV3PagePrediction # failed to identify its superclass
          def to_s: -> String
        end
      end
    end
  end
end
