# lib/mindee/product/fr/payslip/payslip_v2_page.rb
module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV2Page # failed to identify its superclass
          def initialize: (untyped) -> nil
        end
        class PayslipV2PagePrediction # failed to identify its superclass
          def to_s: -> String
        end
      end
    end
  end
end
