# lib/mindee/product/fr/payslip/payslip_v3_employment.rb
module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV3Employment # failed to identify its superclass
          def category: -> untyped
          def coefficient: -> untyped
          def collective_agreement: -> untyped
          def job_title: -> untyped
          def position_level: -> untyped
          def seniority_date: -> untyped
          def start_date: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, untyped]
          def to_s: -> String
        end
      end
    end
  end
end
