# lib/mindee/product/fr/payslip/payslip_v2_bank_account_detail.rb
module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV2BankAccountDetail # failed to identify its superclass
          def bank_name: -> untyped
          def iban: -> untyped
          def swift: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, untyped]
          def to_s: -> String
        end
      end
    end
  end
end
