# TypeProf 0.30.1

# lib/mindee/product/fr/payslip/payslip_v3_employer.rb
module Mindee
  module Product
    module Product::FR
      module Product::FR::Payslip
        class Product::FR::Payslip::PayslipV3Employer # failed to identify its superclass
          def address: -> untyped
          def company_id: -> untyped
          def company_site: -> untyped
          def naf_code: -> untyped
          def name: -> untyped
          def phone_number: -> untyped
          def urssaf_number: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, untyped]
          def to_s: -> String
        end
      end
    end
  end
end
