# lib/mindee/product/../payslip/payslip_v3_page.rb

module Mindee
  module Product
    module FR
      module Payslip
        class PayslipV3Page < Parsing::Common::Page
          def initialize: (Hash[Symbol | String, untyped]) -> void
        end
        class PayslipV3PagePrediction < PayslipV3Document
          def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
          def to_s: -> String
        end
      end
    end
  end
end
