# lib/mindee/v2/parsing/search/search_response.rb

module Mindee
  module V2
    module Parsing
      module Search
        # Deprecated: use `Mindee::V2::Search::Models::ModelSearchResponse` instead.
        class SearchResponse < V2::Search::Models::ModelSearchResponse
        end
      end
    end
  end
end
