# lib/mindee/product/fr/bank_account_details/bank_account_details_v2_document.rb
module Mindee
  module Product
    module FR
      module BankAccountDetails
        class BankAccountDetailsV2Document # failed to identify its superclass
          def account_holders_names: -> untyped
          def bban: -> untyped
          def iban: -> untyped
          def swift_code: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def to_s: -> String
        end
      end
    end
  end
end
