# TypeProf 0.30.1

# lib/mindee/product/fr/bank_account_details/bank_account_details_v2_page.rb
module Mindee
  module Product
    module Product::FR
      module Product::FR::BankAccountDetails
        class Product::FR::BankAccountDetails::BankAccountDetailsV2Page # failed to identify its superclass
          def initialize: (untyped) -> nil
        end
        class Product::FR::BankAccountDetails::BankAccountDetailsV2PagePrediction # failed to identify its superclass
          def to_s: -> String
        end
      end
    end
  end
end
