# lib/mindee/product/fr/bank_account_details/bank_account_details_v2_bban.rb
module Mindee
  module Product
    module FR
      module BankAccountDetails
        class BankAccountDetailsV2Bban # failed to identify its superclass
          def bban_bank_code: -> untyped
          def bban_branch_code: -> untyped
          def bban_key: -> untyped
          def bban_number: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, untyped]
          def to_s: -> String
        end
      end
    end
  end
end
