# lib/mindee/product/../bank_account_details/bank_account_details_v1.rb

module Mindee
  module Product
    module FR
      module BankAccountDetails
        class BankAccountDetailsV1 < Parsing::Common::Inference
          def initialize: (Hash[String | Symbol, untyped]) -> void
        end
      end
    end
  end
end
