# lib/mindee/product/fr/bank_account_details/bank_account_details_v1_document.rb
module Mindee
  module Product
    module FR
      module BankAccountDetails
        class BankAccountDetailsV1Document # failed to identify its superclass
          def account_holder_name: -> untyped
          def iban: -> untyped
          def swift: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def to_s: -> String
        end
      end
    end
  end
end
