# lib/mindee/product/../bank_account_details/bank_account_details_v2_page.rb

module Mindee
  module Product
    module FR
      module BankAccountDetails
        class BankAccountDetailsV2Page < Parsing::Common::Page
          def initialize: (Hash[String | Symbol, untyped]) -> void
        end
        class BankAccountDetailsV2PagePrediction < BankAccountDetailsV2Document
          def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
          def to_s: -> String
        end
      end
    end
  end
end
