# frozen_string_literal: true

require_relative 'product/barcode_reader/barcode_reader_v1'
require_relative 'product/cropper/cropper_v1'
require_relative 'product/financial_document/financial_document_v1'
require_relative 'product/fr/bank_account_details/bank_account_details_v1'
require_relative 'product/fr/bank_account_details/bank_account_details_v2'
require_relative 'product/fr/bank_statement/bank_statement_v2'
require_relative 'product/fr/id_card/id_card_v1'
require_relative 'product/fr/id_card/id_card_v2'
require_relative 'product/international_id/international_id_v2'
require_relative 'product/invoice/invoice_v4'
require_relative 'product/invoice_splitter/invoice_splitter_v1'
require_relative 'product/multi_receipts_detector/multi_receipts_detector_v1'
require_relative 'product/passport/passport_v1'
require_relative 'product/receipt/receipt_v5'
require_relative 'product/resume/resume_v1'
require_relative 'product/universal/universal'
