# lib/mindee/v1/product/business_card/business_card_v1.rb

module Mindee
  module V1
    module Product
    module BusinessCard
      class BusinessCardV1 < Parsing::Common::Inference
        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
      end
    end
  end
end
