# lib/mindee/parsing/standard/amount_field.rb
module Mindee
  module Parsing
    module Standard
      class AmountField < BaseField
        attr_reader value: Float?


        def initialize: (Hash[String | Symbol, untyped], Integer?, ?reconstructed: bool) -> void
        def to_s: -> String
      end
    end
  end
end
