# lib/mindee/parsing/standard/base_field.rb
module Mindee
  module Parsing
    module Standard
      class BaseField < Parsing::Standard::AbstractField
        def initialize: (Hash[String | Symbol, untyped], Integer?, ?reconstructed: bool) -> void
        def value: -> (String | Float | Integer | bool)
        def reconstructed: -> bool
      end
    end
  end
end
