# lib/mindee/parsing/standard/boolean_field.rb
module Mindee
  module Parsing
    module Standard
      class BooleanField # failed to identify its superclass
        def value: -> untyped
        def initialize: (untyped, ?nil, ?reconstructed: false) -> Object
        def to_s: -> String
      end
    end
  end
end
