# lib/mindee/parsing/standard/classification_field.rb
module Mindee
  module Parsing
    module Standard
      class ClassificationField < BaseField
        def value: -> String
      end
    end
  end
end
