# lib/mindee/parsing/standard/date_field.rb
module Mindee
  module Parsing
    module Standard
      class DateField < BaseField
        def date_object: -> DateTime
        def value: -> String?
        def raw: -> String?
        def is_computed: -> bool
        def initialize: (Hash[String | Symbol, untyped], Integer?, ?reconstructed: bool) -> void
      end
    end
  end
end
