# lib/mindee/parsing/standard/locale_field.rb
module Mindee
  module Parsing
    module Standard
      class LocaleField
        def confidence: -> Float?
        def language: -> String?
        def country: -> String?
        def currency: -> String?
        def value: -> String?
        def initialize: (Hash[String | Symbol, untyped], ?Integer?) -> void
        def to_s: -> String
      end
    end
  end
end
