# TypeProf 0.30.1

# lib/mindee/parsing/standard/position_field.rb
module Mindee
  module Parsing
    module Parsing::Standard
      class Parsing::Standard::PositionField
        def polygon: -> untyped
        def value: -> untyped
        def quadrangle: -> nil
        def rectangle: -> nil
        def bounding_box: -> nil
        def initialize: (untyped, untyped) -> untyped
        def to_s: -> String
        def to_quadrilateral: (untyped, String) -> nil
      end
    end
  end
end
