# lib/mindee/parsing/standard/tax_field.rb
module Mindee
  module Parsing
    module Standard
      class TaxField < BaseField
        attr_reader base: Float
        attr_reader code: String
        attr_reader rate: Float
        attr_reader value: Float?

        def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
        def print_float: (Float) -> String
        def to_s: -> String
        def printable_values: -> Hash[untyped, String]
        def to_table_line: -> String
      end
      class Taxes < Array[TaxField]
        def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
        def line_separator: (String) -> String
        def to_s: -> String
      end
    end
  end
end
