# TypeProf 0.30.1

# lib/mindee/product/delivery_note/delivery_note_v1_document.rb
module Mindee
  module Product
    module Product::DeliveryNote
      class Product::DeliveryNote::DeliveryNoteV1Document # failed to identify its superclass
        def customer_address: -> untyped
        def customer_name: -> untyped
        def delivery_date: -> untyped
        def delivery_number: -> untyped
        def supplier_address: -> untyped
        def supplier_name: -> untyped
        def total_amount: -> untyped
        def initialize: (untyped, untyped) -> untyped
        def to_s: -> String
      end
    end
  end
end
