# lib/mindee/product/delivery_note/delivery_note_v1_page.rb

module Mindee
  module Product
    module DeliveryNote
      class DeliveryNoteV1Page < Parsing::Common::Page
        def initialize: (Hash[Symbol | String, untyped]) -> void
      end
      class DeliveryNoteV1PagePrediction < DeliveryNoteV1Document
        def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
        def to_s: -> String
      end
    end
  end
end
