# lib/mindee/product/delivery_note/delivery_note_v1_page.rb
module Mindee
  module Product
    module DeliveryNote
      class DeliveryNoteV1Page # failed to identify its superclass
        def initialize: (untyped) -> nil
      end
      class DeliveryNoteV1PagePrediction # failed to identify its superclass
        def to_s: -> String
      end
    end
  end
end
