# TypeProf 0.30.1

# lib/mindee/product/ind/indian_passport/indian_passport_v1_document.rb
module Mindee
  module Product
    module Product::IND
      module Product::IND::IndianPassport
        class Product::IND::IndianPassport::IndianPassportV1Document # failed to identify its superclass
          def address1: -> untyped
          def address2: -> untyped
          def address3: -> untyped
          def birth_date: -> untyped
          def birth_place: -> untyped
          def country: -> untyped
          def expiry_date: -> untyped
          def file_number: -> untyped
          def gender: -> untyped
          def given_names: -> untyped
          def id_number: -> untyped
          def issuance_date: -> untyped
          def issuance_place: -> untyped
          def legal_guardian: -> untyped
          def mrz1: -> untyped
          def mrz2: -> untyped
          def name_of_mother: -> untyped
          def name_of_spouse: -> untyped
          def old_passport_date_of_issue: -> untyped
          def old_passport_number: -> untyped
          def old_passport_place_of_issue: -> untyped
          def page_number: -> untyped
          def surname: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def to_s: -> String
        end
      end
    end
  end
end
