# lib/mindee/product/ind/indian_passport/indian_passport_v1_page.rb
module Mindee
  module Product
    module IND
      module IndianPassport
        class IndianPassportV1Page # failed to identify its superclass
          def initialize: (untyped) -> nil
        end
        class IndianPassportV1PagePrediction # failed to identify its superclass
          def to_s: -> String
        end
      end
    end
  end
end
