# lib/mindee/product/fr/energy_bill/energy_bill_v1_meter_detail.rb
module Mindee
  module Product
    module FR
      module EnergyBill
        class EnergyBillV1MeterDetail # failed to identify its superclass
          def meter_number: -> untyped
          def meter_type: -> untyped
          def unit: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, untyped]
          def to_s: -> String
        end
      end
    end
  end
end
