module Mindee
  module Product
    module FR
      module EnergyBill
        class EnergyBillV1Subscription < Parsing::Standard::FeatureField
          def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
          def description: -> String
          def end_date: -> String
          def start_date: -> String
          def tax_rate: -> Float
          def total: -> Float
          def unit_price: -> Float
          def printable_values: -> Hash[Symbol | String, untyped]
          def table_printable_values: -> Hash[Symbol | String, untyped]
          def to_table_line: -> String
          def to_s: -> String
        end
      end
    end
  end
end
