# frozen_string_literal: true

module Mindee
  module Product
    module FR
      module EnergyBill
        class EnergyBillV1TaxesAndContributions < Array[EnergyBillV1TaxesAndContribution]
          def initialize: (Array[untyped], Integer?) -> void
          def self.line_items_separator: (String) -> String
          def to_s: -> String
        end
      end
    end
  end
end
