# lib/mindee/product/fr/energy_bill/energy_bill_v1_energy_supplier.rb
module Mindee
  module Product
    module FR
      module EnergyBill
        class EnergyBillV1EnergySupplier # failed to identify its superclass
          def address: -> untyped
          def name: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, untyped]
          def to_s: -> String
        end
      end
    end
  end
end
