module Mindee
  module Product
    module FR
      module BankStatement
        class BankStatementV2Transaction < Parsing::Standard::FeatureField
          def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
          def amount: -> Float
          def date: -> String
          def description: -> String
          def printable_values: -> Hash[Symbol | String, untyped]
          def table_printable_values: -> Hash[Symbol | String, untyped]
          def to_table_line: -> String
          def to_s: -> String
        end
      end
    end
  end
end
