# lib/mindee/product/../bank_statement/bank_statement_v1.rb

module Mindee
  module Product
    module FR
      module BankStatement
        class BankStatementV1 < Parsing::Common::Inference
          def initialize: (Hash[Symbol | String, untyped]) -> void
        end
      end
    end
  end
end
