# lib/mindee/product/fr/bank_statement/bank_statement_v1_transaction.rb
module Mindee
  module Product
    module FR
      module BankStatement
        class BankStatementV1Transaction # failed to identify its superclass
          def amount: -> untyped
          def date: -> untyped
          def description: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, String]
          def to_table_line: -> String
          def to_s: -> String
        end
      end
    end
  end
end
