# lib/mindee/product/fr/bank_statement/bank_statement_v1.rb
module Mindee
  module Product
    module FR
      module BankStatement
        class BankStatementV1 # failed to identify its superclass
          def initialize: (untyped) -> untyped
          def endpoint_name: -> untyped
          def endpoint_version: -> untyped
        end
      end
    end
  end
end
