# lib/mindee/product/fr/bank_statement/bank_statement_v1_page.rb
module Mindee
  module Product
    module FR
      module BankStatement
        class BankStatementV1Page # failed to identify its superclass
          def initialize: (untyped) -> untyped
        end
        class BankStatementV1PagePrediction # failed to identify its superclass
          def to_s: -> String
        end
      end
    end
  end
end
