# lib/mindee/v2/product/ocr/ocr_response.rb

module Mindee
  module V2
    module Product
      module OCR
        class OCRResponse < Parsing::BaseResponse[OCRInference]
          self.@slug: String
          self.@_params_type: singleton(Params::OCRParameters)

          attr_reader inference: Mindee::V2::Product::OCR::OCRInference
          def initialize: (Hash[String | Symbol, untyped]) -> void

          def _params_type: -> singleton(Params::OCRParameters)

          def to_s: -> String
          def self._params_type: () -> singleton(Params::OCRParameters)
          def self.slug: () -> String
        end
      end
    end
  end
end
