module Mindee
  module V2
    module Product
      module OCR
        class OCRPage
          attr_reader words: Array[OCRWord]
          attr_reader content: String

          def initialize: (Hash[String | Symbol, untyped]) -> void
          def to_s: -> String
        end
      end
    end
  end
end
