# lib/v1/mindee/client.rb

module Mindee
  module V1
    OTS_OWNER: String

    class ParseOptions
      attr_accessor all_words: bool
      attr_accessor full_text: bool
      attr_accessor close_file: bool
      attr_accessor page_options: PageOptions
      attr_accessor cropper: bool
      attr_accessor rag: bool
      attr_accessor workflow_id: String?
      attr_accessor initial_delay_sec: Integer | Float
      attr_accessor delay_sec: Integer | Float
      attr_accessor max_retries: Integer

      def initialize: (params: Hash[String | Symbol, untyped]) -> void
    end

    class WorkflowOptions
      attr_accessor document_alias: (String?)
      attr_accessor priority: (Symbol?)
      attr_accessor full_text: bool
      attr_accessor rag: bool?
      attr_accessor public_url: (String?)
      attr_accessor page_options: (PageOptions)
      attr_accessor close_file: bool

      def initialize: (params: Hash[String | Symbol, untyped]) -> void
    end

    class Client
      @api_key: String?

      def initialize: (?api_key: String) -> void

      def logger: () -> Logging

      def parse: (Input::Source::LocalInputSource | Input::Source::URLInputSource, singleton(V1::Parsing::Common::Inference), ?endpoint: (V1::HTTP::Endpoint?), options: ParseOptions | Hash[String | Symbol, untyped]) -> V1::Parsing::Common::ApiResponse

      def parse_sync: (Input::Source::LocalInputSource | Input::Source::URLInputSource, singleton(V1::Parsing::Common::Inference), V1::HTTP::Endpoint, ParseOptions) -> V1::Parsing::Common::ApiResponse

      def enqueue: (Input::Source::LocalInputSource | Input::Source::URLInputSource, singleton(V1::Parsing::Common::Inference), ?endpoint: (V1::HTTP::Endpoint?), options: ParseOptions | Hash[String | Symbol, untyped]) -> V1::Parsing::Common::ApiResponse

      def parse_queued: (String, singleton(V1::Parsing::Common::Inference), ?endpoint: V1::HTTP::Endpoint?) -> V1::Parsing::Common::ApiResponse

      def enqueue_and_parse: (Input::Source::URLInputSource | Input::Source::LocalInputSource, singleton(V1::Parsing::Common::Inference), V1::HTTP::Endpoint, ParseOptions) -> V1::Parsing::Common::ApiResponse

      def execute_workflow: (Input::Source::URLInputSource | Input::Source::LocalInputSource, String, options: (Hash[String | Symbol, untyped] | WorkflowOptions)) -> V1::Parsing::Common::WorkflowResponse

      def load_prediction: (singleton(V1::Parsing::Common::Inference), Input::LocalResponse) -> V1::Parsing::Common::ApiResponse

      def source_from_path: (String, ?repair_pdf: bool) -> Input::Source::PathInputSource

      def source_from_bytes: (String, String, ?repair_pdf: bool) -> Input::Source::BytesInputSource

      def source_from_b64string: (String, String, ?repair_pdf: bool) -> Input::Source::Base64InputSource

      def source_from_file: (File, String, ?repair_pdf: bool) -> Input::Source::FileInputSource

      def source_from_url: (String) -> Input::Source::URLInputSource

      def create_endpoint: (endpoint_name: String, account_name: String, version: String) -> V1::HTTP::Endpoint

      private

      def normalize_parse_options: ((Hash[String | Symbol, untyped] | ParseOptions)) -> ParseOptions

      def process_pdf_if_required: (Input::Source::LocalInputSource, ParseOptions | WorkflowOptions) -> void

      def initialize_endpoint: (singleton(V1::Parsing::Common::Inference), ?endpoint_name: String, ?account_name: String, ?version: String) -> V1::HTTP::Endpoint

      def validate_async_params: (Integer | Float, Integer | Float, Integer) -> void

      def fix_endpoint_name: (singleton(V1::Parsing::Common::Inference), String?) -> String

      def fix_account_name: (String) -> String

      def fix_version: (singleton(V1::Parsing::Common::Inference), String) -> String
    end
  end
end
