module Mindee
  module Product
    module NutritionFactsLabel
      class NutritionFactsLabelV1ServingSize < Parsing::Standard::FeatureField
        def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
        def amount: -> Float
        def unit: -> String
        def printable_values: -> Hash[String | Symbol, untyped]
        def to_s: -> String
      end
    end
  end
end
