module Mindee
  module Product
    module NutritionFactsLabel
      class NutritionFactsLabelV1Sodium < Parsing::Standard::FeatureField
        def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
        def daily_value: -> Float
        def per_100g: -> Float
        def per_serving: -> Float
        def unit: -> String
        def printable_values: -> Hash[Symbol | String, untyped]
        def to_s: -> String
      end
    end
  end
end
