# TypeProf 0.30.1

# lib/mindee/product/nutrition_facts_label/nutrition_facts_label_v1_serving_size.rb
module Mindee
  module Product
    module Product::NutritionFactsLabel
      class Product::NutritionFactsLabel::NutritionFactsLabelV1ServingSize # failed to identify its superclass
        def amount: -> untyped
        def unit: -> untyped
        def initialize: (untyped, untyped) -> untyped
        def printable_values: -> Hash[untyped, String]
        def to_s: -> String
      end
    end
  end
end
