# lib/mindee/product/cropper/cropper_v1_page.rb
module Mindee
  module Product
    module Cropper
      class CropperV1Page # failed to identify its superclass
        def initialize: (untyped) -> nil
      end
      class CropperV1PagePrediction # failed to identify its superclass
        def cropping: -> []
        def initialize: (untyped, untyped) -> Object
        def to_s: -> String
      end
    end
  end
end
