# lib/mindee/product/cropper/cropper_v1.rb

module Mindee
  module Product
    module Cropper
      class CropperV1 < Parsing::Common::Inference
        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
    end
  end
end
