# TypeProf 0.30.1

# lib/mindee/product/cropper/cropper_v1_document.rb
module Mindee
  module Product
    module Product::Cropper
      class Product::Cropper::CropperV1Document # failed to identify its superclass
      end
    end
  end
end
