# lib/mindee/parsing/v2/error_response.rb
module Mindee
  module Parsing
    module V2
      class ErrorResponse
        attr_reader detail: String
        attr_reader status: Integer
        attr_reader code: String
        attr_reader title: String
        attr_reader errors: Array[ErrorItem]
        def initialize: (Hash[String | Symbol, untyped]) -> void

        def as_hash: -> Hash[Symbol, String | Integer]

        def to_s: -> String
      end
    end
  end
end
