# lib/mindee/parsing/v2/error_item.rb
module Mindee
  module Parsing
    module V2
      class ErrorItem
        attr_reader pointer: String
        attr_reader detail: String|nil

        def initialize: (Hash[String|Symbol, untyped]) -> void
      end
    end
  end
end
