# lib/mindee/parsing/v2/inference_response.rb
module Mindee
  module Parsing
    module V2
      class InferenceResponse < Mindee::V2::Parsing::BaseResponse[Mindee::Parsing::V2::Inference]

        self.@_slug: String
        self.@_params_type: singleton(Input::BaseParameters)

        attr_reader inference: Mindee::Parsing::V2::Inference
        def initialize: (Hash[String | Symbol, untyped]) -> void

        def _params_type: -> singleton(Input::BaseParameters)

        def to_s: -> String
        def self._params_type: () -> singleton(Input::BaseParameters)
        def self._slug: () -> String
      end
    end
  end
end
