# lib/mindee/parsing/v2/raw_text.rb
module Mindee
  module Parsing
    module V2
      class RawText
        attr_reader pages: Array[RawTextPage]

        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
    end
  end
end
