# TypeProf 0.30.1

# lib/mindee/parsing/universal/universal_list_field.rb
module Mindee
  module Parsing
    module Parsing::Universal
      class Parsing::Universal::UniversalListField
        include Parsing::Universal
        def page_id: -> untyped
        def page_id=: (untyped) -> untyped
        def values: -> []
        def values=: (untyped) -> []
        def initialize: (untyped, ?nil) -> untyped
        def contents_list: -> Array[untyped]
        def contents_string: (?String) -> String
        def to_s: -> String
      end
    end
  end
end
