# lib/mindee/parsing/universal/universal_list_field.rb
module Mindee
  module Parsing
    module Universal
      class UniversalListField
        def page_id: -> Integer?
        def page_id=: (Integer?) -> untyped
        def values: -> Array[UniversalObjectField | Standard::StringField]
        def values=: (Array[UniversalObjectField | Standard::StringField]) -> Array[UniversalObjectField | Standard::StringField]
        def initialize: (Array[Hash[Symbol | String, untyped]], ?nil) -> untyped
        def contents_list: -> Array[String]
        def contents_string: (?String) -> String
        def to_s: -> String
      end
    end
  end
end
