# frozen_string_literal: true

require_relative 'product/custom/custom_v1'
require_relative 'product/proof_of_address/proof_of_address_v1'
require_relative 'product/financial_document/financial_document_v1'
require_relative 'product/invoice/invoice_v4'
require_relative 'product/cropper/cropper_v1'
require_relative 'product/passport/passport_v1'
require_relative 'product/receipt/receipt_v4'
require_relative 'product/receipt/receipt_v5'
require_relative 'product/eu/license_plate/license_plate_v1'
require_relative 'product/fr/bank_account_details/bank_account_details_v1'
require_relative 'product/fr/bank_account_details/bank_account_details_v2'
require_relative 'product/fr/carte_vitale/carte_vitale_v1'
require_relative 'product/fr/id_card/id_card_v1'
require_relative 'product/fr/id_card/id_card_v2'
require_relative 'product/invoice_splitter/invoice_splitter_v1'
require_relative 'product/us/bank_check/bank_check_v1'
require_relative 'product/us/driver_license/driver_license_v1'
require_relative 'product/us/w9/w9_v1'
