# lib/mindee/parsing/v2/field/inference_fields.rb
module Mindee
  module Parsing
    module V2
      module Field
        class InferenceFields < Hash[String, ListField | ObjectField | SimpleField?]
          attr_reader indent_level: Integer

          def get_list_field: (String) -> ListField
          def get_simple_field: (String) -> SimpleField
          def get_object_field: (String) -> ObjectField
          def logger: () -> Logger
          def initialize: (Hash[String | Symbol, untyped], ?Integer) -> void
          def get: (String) -> (ListField | ObjectField | SimpleField?)
          def to_s: (?Integer) -> String
        end
      end
    end
  end
end
