# lib/mindee/parsing/v2/field/simple_field.rb
module Mindee
  module Parsing
    module V2
      module Field
        class SimpleField < DynamicField
          attr_reader value: String | Integer | Float | bool | nil

          def initialize: (Hash[String | Symbol, untyped], ?Integer) -> void
          def to_s: -> String
          def format_numeric_value: (String | Integer | Float | bool | nil) -> String
        end
      end
    end
  end
end
