# lib/mindee/product/../id_card/id_card_v2_page.rb

module Mindee
  module Product
    module FR
      module IdCard
        class IdCardV2Page < Parsing::Common::Page
          def initialize: (Hash[Symbol | String, untyped]) -> void
        end
        class IdCardV2PagePrediction < IdCardV2Document
          def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
          def document_side: -> Parsing::Standard::ClassificationField
          def document_type: -> Parsing::Standard::ClassificationField
          def to_s: -> String
        end
      end
    end
  end
end
