# lib/mindee/product/fr/id_card/id_card_v1_page.rb
module Mindee
  module Product
    module FR
      module IdCard
        class IdCardV1Page # failed to identify its superclass
          def initialize: (untyped) -> nil
        end
        class IdCardV1PagePrediction # failed to identify its superclass
          def document_side: -> untyped
          def initialize: (untyped, untyped) -> Object
          def to_s: -> String
        end
      end
    end
  end
end
