# lib/mindee/product/../id_card/id_card_v2.rb

module Mindee
  module Product
    module FR
      module IdCard
        class IdCardV2 < Parsing::Common::Inference
          def initialize: (Hash[String | Symbol, untyped]) -> void
        end
      end
    end
  end
end
