# lib/mindee/parsing/v2/field/field_confidence.rb
module Mindee
  module Parsing
    module V2
      module Field
        class FieldConfidence
          attr_reader value: String
          CERTAIN: String
          HIGH: String
          MEDIUM: String
          LOW: String
          VALID_VALUES: Array[String]
          def initialize: (String) -> void
          def self.from_string: (String) -> FieldConfidence
          def to_i: -> Integer
          def to_s: -> String
          def ==: (String | Integer | FieldConfidence) -> bool
          def eql?: (String | Integer | FieldConfidence) -> bool
          def <=: (String | Integer | FieldConfidence) -> bool
          def lteql? : (String | Integer | FieldConfidence) -> bool
          def >=: (String | Integer | FieldConfidence) -> bool
          def gteql?: (String | Integer | FieldConfidence) -> bool
          def inspect: -> String

          def val_to_i: (String) -> Integer
        end
      end
    end
  end
end
