# lib/mindee/v2/parsing/field/object_field.rb
module Mindee
  module V2
    module Parsing
      module Field
        # A field containing a nested set of inference fields.
        class ObjectField < BaseField
          attr_reader fields: InferenceFields
          def initialize: (Hash[String | Symbol, untyped], ?Integer) -> void

          def get_simple_field: (String) -> SimpleField
          def get_list_field: (String) -> ListField
          def get_object_field: (String) -> ObjectField

          def simple_fields: () -> Hash[String, SimpleField]
          def list_fields: () -> Hash[String, ListField]
          def object_fields: () -> Hash[String, ObjectField]

          def multi_str: -> String
          def single_str: -> String
          def to_s: -> String
          def to_s_from_list: -> String
        end
      end
    end
  end
end
