# lib/mindee/v2/parsing/field/simple_field.rb
module Mindee
  module V2
    module Parsing
      module Field
        class SimpleField < BaseField
          attr_reader value: String | Float | bool | nil

          def initialize: (Hash[String | Symbol, untyped], ?Integer) -> void
          def boolean_value: -> (bool | nil)
          def float_value: -> (Float | nil)
          def string_value: -> (String | nil)

          def to_s: -> String
          def format_numeric_value: (Integer | Float) -> String
        end
      end
    end
  end
end
