# lib/mindee/product/../license_plate/license_plate_v1_document.rb

module Mindee
  module Product
    module EU
      module LicensePlate
        class LicensePlateV1Document < Parsing::Common::Prediction
          def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
          def license_plates: -> (Array[Parsing::Standard::StringField])
          def to_s: -> String
        end
      end
    end
  end
end
