# lib/mindee/product/../license_plate/license_plate_v1.rb

module Mindee
  module Product
    module EU
      module LicensePlate
        class LicensePlateV1 < Parsing::Common::Inference
          def initialize: (Hash[Symbol | String, untyped]) -> void
        end
      end
    end
  end
end
