# lib/mindee/product/eu/license_plate/license_plate_v1_document.rb
module Mindee
  module Product
    module EU
      module LicensePlate
        class LicensePlateV1Document # failed to identify its superclass
          def license_plates: -> []
          def initialize: (untyped, untyped) -> untyped
          def to_s: -> String
        end
      end
    end
  end
end
