# TypeProf 0.30.1

# lib/mindee/product/eu/license_plate/license_plate_v1_page.rb
module Mindee
  module Product
    module Product::EU
      module Product::EU::LicensePlate
        class Product::EU::LicensePlate::LicensePlateV1Page # failed to identify its superclass
          def initialize: (untyped) -> nil
        end
        class Product::EU::LicensePlate::LicensePlateV1PagePrediction # failed to identify its superclass
          def to_s: -> String
        end
      end
    end
  end
end
