# lib/mindee/product/business_card/business_card_v1_page.rb

module Mindee
  module Product
    module BusinessCard
      class BusinessCardV1Page < Parsing::Common::Page
        def initialize: (Hash[Symbol | String, untyped]) -> void
      end
      class BusinessCardV1PagePrediction < BusinessCardV1Document
        def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
        def to_s: -> String
      end
    end
  end
end
