# lib/mindee/product/business_card/business_card_v1.rb

module Mindee
  module Product
    module BusinessCard
      class BusinessCardV1 < Parsing::Common::Inference
        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
    end
  end
end
