# lib/mindee/product/business_card/business_card_v1.rb
module Mindee
  module Product
    module BusinessCard
      class BusinessCardV1 # failed to identify its superclass
        def initialize: (untyped) -> untyped
        def endpoint_name: -> untyped
        def endpoint_version: -> untyped
        def has_async: -> untyped
        def has_sync: -> untyped
      end
    end
  end
end
