# TypeProf 0.30.1

# lib/mindee/product/business_card/business_card_v1_document.rb
module Mindee
  module Product
    module Product::BusinessCard
      class Product::BusinessCard::BusinessCardV1Document # failed to identify its superclass
        def address: -> untyped
        def company: -> untyped
        def email: -> untyped
        def fax_number: -> untyped
        def firstname: -> untyped
        def job_title: -> untyped
        def lastname: -> untyped
        def mobile_number: -> untyped
        def phone_number: -> untyped
        def social_media: -> []
        def website: -> untyped
        def initialize: (untyped, untyped) -> untyped
        def to_s: -> String
      end
    end
  end
end
