# lib/mindee/product/business_card/business_card_v1_page.rb
module Mindee
  module Product
    module BusinessCard
      class BusinessCardV1Page # failed to identify its superclass
        def initialize: (untyped) -> nil
      end
      class BusinessCardV1PagePrediction # failed to identify its superclass
        def to_s: -> String
      end
    end
  end
end
