# lib/mindee/http/api_settings_v2.rb
module Mindee
  module HTTP
    class ApiSettingsV2
      MINDEE_V2_API_KEY_ENV_NAME: String
      MINDEE_V2_API_KEY_DEFAULT: String?
      MINDEE_V2_BASE_URL_ENV_NAME: String
      MINDEE_V2_BASE_URL_DEFAULT: String
      MINDEE_V2_REQUEST_TIMEOUT_ENV_NAME: String
      MINDEE_V2_TIMEOUT_DEFAULT: Integer
      USER_AGENT: String

      attr_reader api_key: String?
      attr_reader base_url: String
      attr_reader request_timeout: Integer
      attr_reader user_agent: String

      def initialize: (?api_key: String) -> void
      def check_api_key: -> void
    end
  end
end
