# lib/mindee/http/http_error_handler.rb
module Mindee
  module HTTP
    module ErrorHandler
      def extract_error: (Hash[String | Symbol, untyped]) -> void
      def create_error_obj: (Hash[String | Symbol, untyped]) -> (Hash[String, String] | Hash[String | Symbol, untyped])?
      def handle_error: (String, Hash[String | Symbol, untyped]) -> void
      def handle_v2_error: (Hash[String | Symbol, untyped]) -> void
    end
  end
end
