# lib/mindee/http/http_error_handler.rb
module Mindee
  module HTTP
    module ErrorHandler
      def extract_error: (untyped) -> nil
      def create_error_obj: (untyped) -> (Hash[String, String] | Hash[untyped, untyped])?
      def self.handle_error: (untyped, untyped) -> untyped
    end
  end
end
