# lib/mindee/http/mindee_api_v2.rbs
module Mindee
  module HTTP
    interface _ResponseFactory[T]
      def new: (Hash[String | Symbol, untyped]) -> T
    end

    interface _ProductClass[T]
      def slug: () -> String
      def response_type: () -> _ResponseFactory[T]
      def params_type: () -> singleton(Input::BaseParameters)
    end

    class MindeeApiV2
      attr_reader settings: ApiSettingsV2

      def initialize: (?api_key: String?) -> void

      def req_get_result: [T] (_ProductClass[T] product, String resource) -> T

      def req_post_enqueue: (Input::Source::LocalInputSource | Input::Source::URLInputSource, Input::BaseParameters) -> V2::Parsing::JobResponse
      def req_get_job: (String) -> V2::Parsing::JobResponse
      def process_response: (Net::HTTPResponse?) -> Hash[String | Symbol, untyped]
      def poll: (String) -> Net::HTTPResponse
      def result_req_get: [T] (String, _ProductClass[T] product) -> Net::HTTPResponse
      def enqueue: (Input::Source::LocalInputSource | Input::Source::URLInputSource, Input::BaseParameters) -> Net::HTTPResponse?

      def search_models: (String?, String?) -> Mindee::V2::Parsing::Search::SearchResponse

      private

      def enqueue_form_options: (Array[Array[untyped]], V2::Product::Extraction::Params::ExtractionParameters) -> Array[Array[untyped]]

      def req_get_job_url: (String) -> V2::Parsing::JobResponse
      def req_get_result_url: [T] (_ResponseFactory[T] result_class, String url) -> T

      def req_get_search_models: (String?, String?) -> Net::HTTPResponse

      def uri?: (String) -> bool
    end
  end
end
