# lib/mindee/http/response_validation.rb
module Mindee
  module HTTP
    module ResponseValidation
      def self.valid_sync_response?: (Net::HTTPResponse) -> bool
      def self.valid_async_response?: (Net::HTTPResponse) -> bool
      def self.clean_request!: (Net::HTTPResponse) -> void
    end
  end
end
