# lib/mindee/product/multi_receipts_detector/multi_receipts_detector_v1_page.rb
module Mindee
  module Product
    module MultiReceiptsDetector
      class MultiReceiptsDetectorV1Page # failed to identify its superclass
        def initialize: (untyped) -> nil
      end
      class MultiReceiptsDetectorV1PagePrediction # failed to identify its superclass
        def to_s: -> String
      end
    end
  end
end
