# lib/mindee/product/multi_receipts_detector/multi_receipts_detector_v1.rb
module Mindee
  module Product
    module MultiReceiptsDetector
      class MultiReceiptsDetectorV1 # failed to identify its superclass
        def initialize: (untyped) -> untyped
        def endpoint_name: -> untyped
        def endpoint_version: -> untyped
        def has_async: -> untyped
        def has_sync: -> untyped
      end
    end
  end
end
