# lib/mindee/product/multi_receipts_detector/multi_receipts_detector_v1_document.rb

module Mindee
  module Product
    module MultiReceiptsDetector
      class MultiReceiptsDetectorV1Document < Parsing::Common::Prediction
        def initialize: (Hash[Symbol | String, untyped], ?Integer?) -> void
        def receipts: -> Array[Parsing::Standard::PositionField]
        def to_s: -> String
      end
    end
  end
end
