# lib/mindee/parsing/common/extras/cropper_extra.rb
module Mindee
  module Parsing
    module Common
      module Extras
        class CropperExtra
          attr_reader croppings: Array[Standard::PositionField]

          def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
          def to_s: -> String
        end
      end
    end
  end
end
