# TypeProf 0.30.1

# lib/mindee/parsing/common/extras/full_text_ocr_extra.rb
module Mindee
  module Parsing
    module Parsing::Common
      module Parsing::Common::Extras
        class Parsing::Common::Extras::FullTextOCRExtra
          def contents: -> untyped
          def language: -> untyped
          def initialize: (untyped) -> nil
          def to_s: -> String
        end
      end
    end
  end
end
