# lib/mindee/parsing/common/extras/rag_extra.rb

module Mindee
  module Parsing
    module Common
      module Extras
        class RAGExtra
          def matching_document_id: -> String?
          def initialize: (untyped) -> nil
          def to_s: -> String
        end
      end
    end
  end
end