# lib/mindee/geometry/min_max.rb
module Mindee
  module Geometry
    class MinMax
      attr_reader max: Float
      attr_reader min: Float

      def initialize: (Float, Float) -> void
    end
  end
end
