# lib/mindee/geometry/point.rb
module Mindee
  module Geometry
    class Point
      attr_accessor x: Float
      attr_accessor y: Float

      def initialize: (Float, Float) -> void
      def []: (Integer) -> Float
    end
  end
end
