# lib/mindee/geometry/quadrilateral.rb
module Mindee
  module Geometry
    class Quadrilateral
      def top_left: -> Point
      def top_left=: (Point) -> bool
      def top_right: -> Point
      def top_right=: (Point) -> untyped
      def bottom_right: -> Point
      def bottom_right=: (Point) -> untyped
      def bottom_left: -> Point
      def bottom_left=: (Point) -> untyped
      def initialize: (Point, Point, Point, Point) -> void
      def []: (Integer) -> Point
      def size: -> Integer
    end
  end
end
