# lib/mindee/geometry/quadrilateral.rb
module Mindee
  module Geometry
    class Quadrilateral
      attr_accessor bottom_left: Point
      attr_accessor bottom_right: Point
      attr_accessor top_left: Point
      attr_accessor top_right: Point

      def initialize: (Point, Point, Point, Point) -> void
      def []: (Integer) -> Point
      def size: -> Integer
    end
  end
end
