# TypeProf 0.30.1

# lib/mindee/geometry/quadrilateral.rb
module Mindee
  module Geometry
    class Geometry::Quadrilateral
      def top_left: -> untyped
      def top_left=: (untyped) -> untyped
      def top_right: -> untyped
      def top_right=: (untyped) -> untyped
      def bottom_right: -> untyped
      def bottom_right=: (untyped) -> untyped
      def bottom_left: -> untyped
      def bottom_left=: (untyped) -> untyped
      def initialize: (untyped, untyped, untyped, untyped) -> untyped
      def []: (untyped) -> bot
      def size: -> Integer
    end
  end
end
