# lib/mindee/product/us/w9/w9_v1_document.rb
module Mindee
  module Product
    module US
      module W9
        class W9V1Document # failed to identify its superclass
        end
      end
    end
  end
end
