# lib/mindee/product/invoice_splitter/invoice_splitter_v1.rb

module Mindee
  module Product
    module InvoiceSplitter
      class InvoiceSplitterV1 < Parsing::Common::Inference
        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
    end
  end
end
