module Mindee
  module Product
    module InvoiceSplitter
      class InvoiceSplitterV1InvoicePageGroup < Parsing::Standard::FeatureField
        def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
        def page_indexes: -> Array[Integer]
        def printable_values: -> Hash[Symbol | String, untyped]
        def table_printable_values: -> Hash[Symbol | String, untyped]
        def to_table_line: -> String
        def to_s: -> String
      end
    end
  end
end
