# lib/mindee/product/invoice_splitter/invoice_splitter_v1_page.rb
module Mindee
  module Product
    module InvoiceSplitter
      class InvoiceSplitterV1Page # failed to identify its superclass
        def initialize: (untyped) -> untyped
      end
      class InvoiceSplitterV1PagePrediction # failed to identify its superclass
        def to_s: -> String
      end
    end
  end
end
