# TypeProf 0.30.1

# lib/mindee/product/invoice_splitter/invoice_splitter_v1.rb
module Mindee
  module Product
    module Product::InvoiceSplitter
      class Product::InvoiceSplitter::InvoiceSplitterV1 # failed to identify its superclass
        def initialize: (untyped) -> untyped
        def endpoint_name: -> untyped
        def endpoint_version: -> untyped
        def has_async: -> untyped
        def has_sync: -> untyped
      end
    end
  end
end
