# lib/mindee/product/invoice_splitter/invoice_splitter_v1_document.rb

module Mindee
  module Product
    module InvoiceSplitter
      class InvoiceSplitterV1Document < Parsing::Common::Prediction
        def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
        def invoice_page_groups: -> (Product::InvoiceSplitter::InvoiceSplitterV1InvoicePageGroups)
        def invoice_page_groups_separator: (String) -> String
        def invoice_page_groups_to_s: -> String
        def to_s: -> String
      end
    end
  end
end
