# lib/mindee/pdf/extracted_pdf.rb
module Mindee
  module PDF
    module PDFExtractor
      class ExtractedPDF
        attr_reader pdf_bytes: StringIO
        attr_reader filename: String
        def initialize: (StringIO, String) -> void
        def page_count: -> Integer
        def write_to_file: (String, ?override: bool) -> Integer
        def as_input_source: -> Input::Source::BytesInputSource
      end
    end
  end
end
