# lib/mindee/pdf/pdf_compressor.rb
PDFReader: untyped
module Mindee
  module PDF
    module
      def self.compress_pdf: (untyped, ?quality: Integer, ?force_source_text_compression: false, ?disable_source_text: true) -> StringIO
      def self.process_pdf_pages: (untyped, Integer) -> untyped
      def self.create_output_pdf: (untyped, true, untyped) -> untyped
      def self.inject_text: (untyped, untyped) -> nil
      def self.process_pdf_page: (untyped, untyped, Integer, untyped) -> untyped
    end
  end
end
