# lib/mindee/pdf/pdf_compressor.rb
PDFReader: untyped
PDF: untyped
module Mindee
  module PDF
    module PDFCompressor
      def self.logger: () -> Logger
      def self.compress_pdf: (StringIO | File, ?quality: Integer, ?force_source_text_compression: bool, ?disable_source_text: bool) -> (StringIO | File)
      def self.process_pdf_pages: (Origami::PDF, Integer) -> Array[Origami::Page]
      def self.create_output_pdf: (Array[Origami::Page], bool, StringIO | File) -> Origami::PDF
      def self.inject_text: (StringIO | File, Array[Origami::Page]) -> nil
      def self.process_pdf_page: (StringIO, Integer, Integer, Array[Integer]?) -> Origami::Page
    end
  end
end
