# lib/mindee/pdf/pdf_processor.rb
module Mindee
  module PDF
    module PDFProcessor
      DEFAULT_OPTIONS: Hash[Symbol, untyped]
      def self.parse: (StringIO, Hash[Symbol, Array[untyped]]) -> nil
      def self.indexes_from_keep: (Array[Integer], Array[untyped]) -> (Array[Integer] | Array[untyped])
      def self.indexes_from_remove: (Array[Integer], Array[untyped]) -> (Array[Integer] | Array[untyped])
      def self.open_pdf: (StringIO) -> untyped
      def self.get_page: (untyped, untyped) -> nil
    end
  end
end
