# lib/mindee/pdf/pdf_extractor.rb
module Mindee
  module PDF
    module PDFExtractor
      class PDFExtractor
        attr_reader filename: String
        attr_reader source_pdf: StringIO

        def initialize: (Input::Source::LocalInputSource) -> void
        def page_count: -> Integer
        def cut_pages: (Array[Integer]) -> StringIO
        def extract_sub_documents: (Array[Array[Integer]]) -> Array[ExtractedPDF]
        def extract_invoices: (Array[Product::InvoiceSplitter::InvoiceSplitterV1InvoicePageGroup] | Array [Array[Integer]], ?strict: bool) -> Array[ExtractedPDF]
      end
    end
  end
end
