module Mindee
  module V2
    module Product
      module Split
        class SplitRange
          attr_reader extraction_response: Extraction::ExtractionResponse
          attr_reader page_range: Array[Integer]
          attr_reader document_type: String

          def initialize: (Hash[String | Symbol, untyped]) -> void

          def extract_from_file: (Input::Source::LocalInputSource) -> PDF::ExtractedPDF

          def to_s: -> String
        end
      end
    end
  end
end
