# lib/mindee/input/sources/base64_input_source.rb
module Mindee
  module Input
    module Source
      class Base64InputSource < LocalInputSource
        def initialize: (String, String, ?fix_pdf: bool) -> void
        def read_contents: (?close: bool) -> [String, String, Hash[Symbol, untyped]]
      end
    end
  end
end
