# lib/mindee/input/sources/base64_input_source.rb
module Mindee
  module Input
    module Source
      class Base64InputSource # failed to identify its superclass
        def initialize: (untyped, untyped, ?fix_pdf: bool) -> untyped
        def read_contents: (?close: true) -> [String, String, Hash[:filename, untyped]]
      end
    end
  end
end
