# lib/mindee/input/sources/base64_input_source.rb
module Mindee
  module Input
    module Source
      class Base64InputSource < LocalInputSource
        def initialize: (String, String, ?repair_pdf: bool) -> void
        def read_contents: (?close: bool) -> [String?, Hash[:filename, String]]
      end
    end
  end
end
