# lib/mindee/input/sources/bytes_input_source.rb
module Mindee
  module Input
    module Source
      class BytesInputSource < LocalInputSource
        def initialize: (String, String, ?repair_pdf: bool) -> void
      end
    end
  end
end
