# lib/mindee/input/sources/file_input_source.rb
module Mindee
  module Input
    module Source
      class FileInputSource # failed to identify its superclass
        def initialize: (untyped, untyped, fix_pdf: bool) -> untyped
      end
    end
  end
end
