# lib/mindee/input/sources/local_input_source.rb
module Mindee
  module Input
    module Source
      ALLOWED_MIME_TYPES: Array[String]
      class LocalInputSource
        def filename: -> String
        def file_mimetype: -> String
        def io_stream: -> StringIO
        def initialize: (StringIO | File, String, ?fix_pdf: bool) -> void
        def logger: () -> untyped
        def rescue_broken_pdf: (StringIO) -> StringIO
        def pdf?: -> bool
        def process_pdf: (PageOptions) -> StringIO?
        def read_contents: (?close: bool) -> [String, String?, Hash[:filename, String]]
        def count_pages: -> Integer
        def compress!: (?quality: Integer, ?max_width: Integer?, ?max_height: Integer?, ?force_source_text: bool, ?disable_source_text: bool) -> Integer
        def source_text?: -> bool?
      end
      def self.convert_to_unicode_escape: (String) -> String
    end
  end
end
