# lib/mindee/input/sources/url_input_source.rb
module Mindee
  module Input
    module Source
      class URLInputSource
        def url: -> String
        def logger: () -> Logger
        def initialize: (String) -> void
        def write_to_file: (String, ?filename: String?, ?username: String?, ?password: String?, ?token: String?, ?max_redirects: Integer) -> String
        def as_local_input_source: (?filename: String?, ?username: String?, ?password: String?, ?token: String?, ?max_redirects: Integer) -> BytesInputSource?
        def fetch_file_content: (?username: String?, ?password: String?, ?token: String?, ?max_redirects: Integer) -> String
        def extract_filename_from_url: (::URI::File | ::URI::FTP | ::URI::HTTP | ::URI::HTTPS | ::URI::LDAP | ::URI::LDAPS | ::URI::MailTo | ::URI::WS | ::URI::WSS | ::URI::Generic) -> String
        def fill_filename: (String?) -> String
        def make_request: (URI::Generic, Net::HTTP::Get, Integer) -> Net::HTTPRedirection
        def get_file_extension: (String) -> String?
        def generate_file_name: (?extension: String?) -> String
      end
    end
  end
end
