# TypeProf 0.30.1

# lib/mindee/product/us/healthcare_card/healthcare_card_v1_page.rb
module Mindee
  module Product
    module Product::US
      module Product::US::HealthcareCard
        class Product::US::HealthcareCard::HealthcareCardV1Page # failed to identify its superclass
          def initialize: (untyped) -> nil
        end
        class Product::US::HealthcareCard::HealthcareCardV1PagePrediction # failed to identify its superclass
          def to_s: -> String
        end
      end
    end
  end
end
