# lib/mindee/product/../healthcare_card/healthcare_card_v1_page.rb

module Mindee
  module Product
    module US
      module HealthcareCard
        class HealthcareCardV1Page < Parsing::Common::Page
          def initialize: (Hash[Symbol | String, untyped]) -> void
        end
        class HealthcareCardV1PagePrediction < HealthcareCardV1Document
          def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
          def to_s: -> String
        end
      end
    end
  end
end
