# frozen_string_literal: true

module Mindee
  module Product
    module US
      module HealthcareCard
        class HealthcareCardV1Copays < Array[untyped]
          def initialize: (Array[untyped], Integer?) -> void
          def self.line_items_separator: (String) -> String
          def to_s: -> String
        end
      end
    end
  end
end
