# lib/mindee/product/us/healthcare_card/healthcare_card_v1_copay.rb
module Mindee
  module Product
    module US
      module HealthcareCard
        class HealthcareCardV1Copay # failed to identify its superclass
          def service_fees: -> untyped
          def service_name: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, String]
          def table_printable_values: -> Hash[untyped, String]
          def to_table_line: -> String
          def to_s: -> String
        end
      end
    end
  end
end
