# lib/mindee/product/us/healthcare_card/healthcare_card_v1_document.rb
module Mindee
  module Product
    module US
      module HealthcareCard
        class HealthcareCardV1Document # failed to identify its superclass
          def company_name: -> untyped
          def copays: -> []
          def dependents: -> []
          def enrollment_date: -> untyped
          def group_number: -> untyped
          def issuer80840: -> untyped
          def member_id: -> untyped
          def member_name: -> untyped
          def payer_id: -> untyped
          def rx_bin: -> untyped
          def rx_grp: -> untyped
          def rx_pcn: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def to_s: -> String
          def copays_separator: (String) -> String
          def copays_to_s: -> String
        end
      end
    end
  end
end
