# lib/mindee/product/../healthcare_card/healthcare_card_v1.rb

module Mindee
  module Product
    module US
      module HealthcareCard
        class HealthcareCardV1 < Parsing::Common::Inference
          def initialize: (Hash[String | Symbol, untyped]) -> void
        end
      end
    end
  end
end
