# lib/mindee/product/us/healthcare_card/healthcare_card_v1_page.rb
module Mindee
  module Product
    module US
      module HealthcareCard
        class HealthcareCardV1Page # failed to identify its superclass
          def initialize: (untyped) -> nil
        end
        class HealthcareCardV1PagePrediction # failed to identify its superclass
          def to_s: -> String
        end
      end
    end
  end
end
