module Mindee
  module Product
    module US
      module HealthcareCard
        class HealthcareCardV1Copay < Parsing::Standard::FeatureField
          def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
          def service_fees: -> Float
          def service_name: -> String
          def printable_values: -> Hash[String | Symbol, untyped]
          def table_printable_values: -> Hash[String | Symbol, untyped]
          def to_table_line: -> String
          def to_s: -> String
        end
      end
    end
  end
end
