# TypeProf 0.30.1

# lib/mindee/product/receipt/receipt_v5.rb
module Mindee
  module Product
    module Product::Receipt
      class Product::Receipt::ReceiptV5 # failed to identify its superclass
        def initialize: (untyped) -> untyped
        def endpoint_name: -> untyped
        def endpoint_version: -> untyped
        def has_async: -> untyped
        def has_sync: -> untyped
      end
    end
  end
end
