# TypeProf 0.30.1

# lib/mindee/product/receipt/receipt_v5_document.rb
module Mindee
  module Product
    module Product::Receipt
      class Product::Receipt::ReceiptV5Document # failed to identify its superclass
        def category: -> untyped
        def date: -> untyped
        def document_type: -> untyped
        def line_items: -> []
        def locale: -> untyped
        def receipt_number: -> untyped
        def subcategory: -> untyped
        def supplier_address: -> untyped
        def supplier_company_registrations: -> []
        def supplier_name: -> untyped
        def supplier_phone_number: -> untyped
        def taxes: -> untyped
        def time: -> untyped
        def tip: -> untyped
        def total_amount: -> untyped
        def total_net: -> untyped
        def total_tax: -> untyped
        def initialize: (untyped, untyped) -> untyped
        def to_s: -> String
        def line_items_separator: (String) -> String
        def line_items_to_s: -> String
      end
    end
  end
end
