# lib/mindee/product/receipt/receipt_v5_page.rb

module Mindee
  module Product
    module Receipt
      class ReceiptV5Page < Parsing::Common::Page
        def initialize: (Hash[Symbol | String, untyped]) -> void
      end
      class ReceiptV5PagePrediction < ReceiptV5Document
        def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
        def to_s: -> String
      end
    end
  end
end
