# TypeProf 0.30.1

# lib/mindee/product/receipt/receipt_v5_page.rb
module Mindee
  module Product
    module Product::Receipt
      class Product::Receipt::ReceiptV5Page # failed to identify its superclass
        def initialize: (untyped) -> nil
      end
      class Product::Receipt::ReceiptV5PagePrediction # failed to identify its superclass
        def to_s: -> String
      end
    end
  end
end
