# lib/mindee/v1/product/nutrition_facts_label/nutrition_facts_label_v1.rb

module Mindee
  module V1
    module Product
    module NutritionFactsLabel
      class NutritionFactsLabelV1 < Parsing::Common::Inference
        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
      end
    end
  end
end
