module Mindee
  module V2
    module Product
      class BaseProduct
        self.@slug: String
        self.@params_type: singleton(Input::BaseParameters)
        self.@response_type: singleton(Parsing::BaseResponse)

        def self._params_type: () -> singleton(Input::BaseParameters)

        attr_reader self.slug: String
        attr_reader self.params_type: singleton(Input::BaseParameters)
        attr_reader self.response_type: singleton(Parsing::BaseResponse)

        def initialize: -> void
      end
    end
  end
end
