# frozen_string_literal: true

require_relative 'custom/custom_v1'
require_relative 'proof_of_address/proof_of_address_v1'
require_relative 'financial_document/financial_document_v1'
require_relative 'invoice/invoice_v4'
require_relative 'passport/passport_v1'
require_relative 'receipt/receipt_v4'
require_relative 'receipt/receipt_v5'
require_relative 'eu/license_plate/license_plate_v1'
require_relative 'us/bank_check/bank_check_v1'
require_relative 'fr/bank_account_details/bank_account_details_v1'
require_relative 'fr/carte_vitale/carte_vitale_v1'
require_relative 'fr/id_card/id_card_v1'
require_relative 'invoice_splitter/invoice_splitter_v1'
