# lib/mindee/product/barcode_reader/barcode_reader_v1_document.rb
module Mindee
  module Product
    module BarcodeReader
      class BarcodeReaderV1Document # failed to identify its superclass
        def codes_1d: -> []
        def codes_2d: -> []
        def initialize: (untyped, untyped) -> untyped
        def to_s: -> String
      end
    end
  end
end
