# lib/mindee/product/barcode_reader/barcode_reader_v1.rb

module Mindee
  module Product
    module BarcodeReader
      class BarcodeReaderV1 < Parsing::Common::Inference
        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
    end
  end
end
