# lib/mindee/product/barcode_reader/barcode_reader_v1_page.rb
module Mindee
  module Product
    module BarcodeReader
      class BarcodeReaderV1Page # failed to identify its superclass
        def initialize: (untyped) -> nil
      end
      class BarcodeReaderV1PagePrediction # failed to identify its superclass
        def to_s: -> String
      end
    end
  end
end
