# lib/mindee/product/barcode_reader/barcode_reader_v1_page.rb

module Mindee
  module Product
    module BarcodeReader
      class BarcodeReaderV1Page < Parsing::Common::Page
        def initialize: (Hash[Symbol | String, untyped]) -> void
      end
      class BarcodeReaderV1PagePrediction < BarcodeReaderV1Document
        def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
        def to_s: -> String
      end
    end
  end
end
