# lib/mindee/v2/parsing/base_response.rb

module Mindee
  module V2
    module Parsing
      class BaseResponse[T] < Mindee::V2::Parsing::CommonResponse
        attr_reader inference: T
      end
    end
  end
end
