# lib/mindee/v2/parsing/base_inference.rb

module Mindee
  module V2
    module Parsing
      class BaseInference
        attr_reader job: Mindee::V2::Parsing::InferenceJob
        attr_reader file: Mindee::V2::Parsing::InferenceFile
        attr_reader id: String
        attr_reader model: Mindee::V2::Parsing::InferenceModel

        def initialize: (Hash[String | Symbol, untyped]) -> void

        def to_s: -> String
      end
    end
  end
end
