# lib/mindee/v2/parsing/base_response.rb

module Mindee
  module V2
    module Parsing
      class BaseResponse[T] < Mindee::Parsing::V2::CommonResponse
        self.@_slug: String
        self.@_params_type: singleton(Input::BaseParameters)
        attr_reader inference: T
      end
    end
  end
end
