# lib/mindee/v2/parsing/common_response.rb
module Mindee
  module V2
    module Parsing
      class CommonResponse
        attr_reader raw_http: String

        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
    end
  end
end
