# lib/mindee/product/international_id/international_id_v2_document.rb
module Mindee
  module Product
    module InternationalId
      class InternationalIdV2Document # failed to identify its superclass
        def address: -> untyped
        def birth_date: -> untyped
        def birth_place: -> untyped
        def country_of_issue: -> untyped
        def document_number: -> untyped
        def document_type: -> untyped
        def expiry_date: -> untyped
        def given_names: -> []
        def issue_date: -> untyped
        def mrz_line1: -> untyped
        def mrz_line2: -> untyped
        def mrz_line3: -> untyped
        def nationality: -> untyped
        def personal_number: -> untyped
        def sex: -> untyped
        def state_of_issue: -> untyped
        def surnames: -> []
        def initialize: (untyped, untyped) -> untyped
        def to_s: -> String
      end
    end
  end
end
