# lib/mindee/product/international_id/international_id_v2.rb
module Mindee
  module Product
    module InternationalId
      class InternationalIdV2 # failed to identify its superclass
        def initialize: (untyped) -> untyped
        def endpoint_name: -> untyped
        def endpoint_version: -> untyped
        def has_async: -> untyped
        def has_sync: -> untyped
      end
    end
  end
end
