# lib/mindee/product/international_id/international_id_v2_page.rb
module Mindee
  module Product
    module InternationalId
      class InternationalIdV2Page # failed to identify its superclass
        def initialize: (untyped) -> nil
      end
      class InternationalIdV2PagePrediction # failed to identify its superclass
        def to_s: -> String
      end
    end
  end
end
