# lib/mindee/product/international_id/international_id_v2_page.rb

module Mindee
  module Product
    module InternationalId
      class InternationalIdV2Page < Parsing::Common::Page
        def initialize: (Hash[Symbol | String, untyped]) -> void
      end
      class InternationalIdV2PagePrediction < InternationalIdV2Document
        def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
        def to_s: -> String
      end
    end
  end
end
