# lib/mindee/product/us/us_mail/us_mail_v3_page.rb
module Mindee
  module Product
    module US
      module UsMail
        class UsMailV3Page # failed to identify its superclass
          def initialize: (untyped) -> nil
        end
        class UsMailV3PagePrediction # failed to identify its superclass
          def to_s: -> String
        end
      end
    end
  end
end
