# TypeProf 0.30.1

# lib/mindee/product/us/us_mail/us_mail_v2_page.rb
module Mindee
  module Product
    module Product::US
      module Product::US::UsMail
        class Product::US::UsMail::UsMailV2Page # failed to identify its superclass
          def initialize: (untyped) -> nil
        end
        class Product::US::UsMail::UsMailV2PagePrediction # failed to identify its superclass
          def to_s: -> String
        end
      end
    end
  end
end
