# lib/mindee/product/us/us_mail/us_mail_v3.rb
module Mindee
  module Product
    module US
      module UsMail
        class UsMailV3 # failed to identify its superclass
          def initialize: (untyped) -> untyped
          def endpoint_name: -> untyped
          def endpoint_version: -> untyped
          def has_async: -> untyped
          def has_sync: -> untyped
        end
      end
    end
  end
end
