# lib/mindee/product/../us_mail/us_mail_v2_page.rb

module Mindee
  module Product
    module US
      module UsMail
        class UsMailV2Page < Parsing::Common::Page
          def initialize: (Hash[String | Symbol, untyped]) -> void
        end
        class UsMailV2PagePrediction < UsMailV2Document
          def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
          def to_s: -> String
        end
      end
    end
  end
end
