# lib/mindee/product/../us_mail/us_mail_v2.rb

module Mindee
  module Product
    module US
      module UsMail
        class UsMailV2 < Parsing::Common::Inference
          def initialize: (Hash[Symbol | String, untyped]) -> void
        end
      end
    end
  end
end
