# frozen_string_literal: true

module Mindee
  module Product
    module US
      module UsMail
        class UsMailV2RecipientAddresses < Array[UsMailV2RecipientAddress]
          def initialize: (Array[untyped], Integer?) -> void
          def self.line_items_separator: (String) -> String
          def to_s: -> String
        end
      end
    end
  end
end
