# lib/mindee/product/us/us_mail/us_mail_v3_document.rb
module Mindee
  module Product
    module US
      module UsMail
        class UsMailV3Document # failed to identify its superclass
          def is_return_to_sender: -> untyped
          def recipient_addresses: -> []
          def recipient_names: -> []
          def sender_address: -> untyped
          def sender_name: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def to_s: -> String
          def recipient_addresses_separator: (String) -> String
          def recipient_addresses_to_s: -> String
        end
      end
    end
  end
end
