# lib/mindee/product/us/us_mail/us_mail_v3_sender_address.rb
module Mindee
  module Product
    module US
      module UsMail
        class UsMailV3SenderAddress # failed to identify its superclass
          def city: -> untyped
          def complete: -> untyped
          def postal_code: -> untyped
          def state: -> untyped
          def street: -> untyped
          def initialize: (untyped, untyped) -> untyped
          def printable_values: -> Hash[untyped, untyped]
          def to_s: -> String
        end
      end
    end
  end
end
