# lib/mindee/product/../bank_check/bank_check_v1_page.rb

module Mindee
  module Product
    module US
      module BankCheck
        class BankCheckV1Page < Parsing::Common::Page
          def initialize: (Hash[String | Symbol, untyped]) -> void
        end
        class BankCheckV1PagePrediction < BankCheckV1Document
          def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
          def check_position: -> Parsing::Standard::PositionField
          def signatures_positions: -> Array[Parsing::Standard::PositionField]
          def to_s: -> String
        end
      end
    end
  end
end
