# lib/mindee/v1/product/receipt/receipt_v5.rb

module Mindee
  module V1
    module Product
    module Receipt
      class ReceiptV5 < Parsing::Common::Inference
        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
      end
    end
  end
end
