# lib/mindee/product/driver_license/driver_license_v1.rb

module Mindee
  module Product
    module DriverLicense
      class DriverLicenseV1 < Parsing::Common::Inference
        def initialize: (Hash[Symbol | String, untyped]) -> void
      end
    end
  end
end
