# lib/mindee/product/driver_license/driver_license_v1_page.rb
module Mindee
  module Product
    module DriverLicense
      class DriverLicenseV1Page # failed to identify its superclass
        def initialize: (untyped) -> nil
      end
      class DriverLicenseV1PagePrediction # failed to identify its superclass
        def to_s: -> String
      end
    end
  end
end
