# lib/mindee/product/driver_license/driver_license_v1_document.rb
module Mindee
  module Product
    module DriverLicense
      class DriverLicenseV1Document # failed to identify its superclass
        def category: -> untyped
        def country_code: -> untyped
        def date_of_birth: -> untyped
        def dd_number: -> untyped
        def expiry_date: -> untyped
        def first_name: -> untyped
        def id: -> untyped
        def issued_date: -> untyped
        def issuing_authority: -> untyped
        def last_name: -> untyped
        def mrz: -> untyped
        def place_of_birth: -> untyped
        def state: -> untyped
        def initialize: (untyped, untyped) -> untyped
        def to_s: -> String
      end
    end
  end
end
