# lib/mindee/product/resume/resume_v1_certificate.rb
module Mindee
  module Product
    module Resume
      class ResumeV1Certificate # failed to identify its superclass
        def grade: -> untyped
        def name: -> untyped
        def provider: -> untyped
        def year: -> untyped
        def initialize: (untyped, untyped) -> untyped
        def printable_values: -> Hash[untyped, untyped]
        def table_printable_values: -> Hash[untyped, untyped]
        def to_table_line: -> String
        def to_s: -> String
      end
    end
  end
end
