# lib/mindee/product/resume/resume_v1_page.rb

module Mindee
  module Product
    module Resume
      class ResumeV1Page < Parsing::Common::Page
        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
      class ResumeV1PagePrediction < ResumeV1Document
        def initialize: (Hash[String | Symbol, untyped], Integer?) -> void
        def to_s: -> String
      end
    end
  end
end
