# lib/mindee/product/resume/resume_v1_page.rb
module Mindee
  module Product
    module Resume
      class ResumeV1Page # failed to identify its superclass
        def initialize: (untyped) -> nil
      end
      class ResumeV1PagePrediction # failed to identify its superclass
        def to_s: -> String
      end
    end
  end
end
