module Mindee
  module Product
    module Resume
      class ResumeV1Education < Parsing::Standard::FeatureField
        def initialize: (Hash[Symbol | String, untyped], Integer?) -> void
        def degree_domain: -> String
        def degree_type: -> String
        def end_month: -> String
        def end_year: -> String
        def school: -> String
        def start_month: -> String
        def start_year: -> String
        def printable_values: -> Hash[Symbol | String, untyped]
        def table_printable_values: -> Hash[Symbol | String, untyped]
        def to_table_line: -> String
        def to_s: -> String
      end
    end
  end
end
