# TypeProf 0.30.1

# lib/mindee/product/resume/resume_v1_education.rb
module Mindee
  module Product
    module Product::Resume
      class Product::Resume::ResumeV1Education # failed to identify its superclass
        def degree_domain: -> untyped
        def degree_type: -> untyped
        def end_month: -> untyped
        def end_year: -> untyped
        def school: -> untyped
        def start_month: -> untyped
        def start_year: -> untyped
        def initialize: (untyped, untyped) -> untyped
        def printable_values: -> Hash[untyped, untyped]
        def table_printable_values: -> Hash[untyped, untyped]
        def to_table_line: -> String
        def to_s: -> String
      end
    end
  end
end
