# lib/mindee/product/resume/resume_v1.rb

module Mindee
  module Product
    module Resume
      class ResumeV1 < Parsing::Common::Inference
        def initialize: (Hash[String | Symbol, untyped]) -> void
      end
    end
  end
end
