# lib/mindee/product/resume/resume_v1_document.rb
module Mindee
  module Product
    module Resume
      class ResumeV1Document # failed to identify its superclass
        def address: -> untyped
        def certificates: -> []
        def document_language: -> untyped
        def document_type: -> untyped
        def education: -> []
        def email_address: -> untyped
        def given_names: -> []
        def hard_skills: -> []
        def job_applied: -> untyped
        def languages: -> []
        def nationality: -> untyped
        def phone_number: -> untyped
        def profession: -> untyped
        def professional_experiences: -> []
        def social_networks_urls: -> []
        def soft_skills: -> []
        def surnames: -> []
        def initialize: (untyped, untyped) -> untyped
        def to_s: -> String
        def social_networks_urls_separator: (String) -> String
        def social_networks_urls_to_s: -> String
        def languages_separator: (String) -> String
        def languages_to_s: -> String
        def education_separator: (String) -> String
        def education_to_s: -> String
        def professional_experiences_separator: (String) -> String
        def professional_experiences_to_s: -> String
        def certificates_separator: (String) -> String
        def certificates_to_s: -> String
      end
    end
  end
end
