# lib/mindee/product/resume/resume_v1_language.rb
module Mindee
  module Product
    module Resume
      class ResumeV1Language # failed to identify its superclass
        def language: -> untyped
        def level: -> untyped
        def initialize: (untyped, untyped) -> untyped
        def printable_values: -> Hash[untyped, untyped]
        def table_printable_values: -> Hash[untyped, untyped]
        def to_table_line: -> String
        def to_s: -> String
      end
    end
  end
end
