# lib/mindee/product/resume/resume_v1_professional_experience.rb
module Mindee
  module Product
    module Resume
      class ResumeV1ProfessionalExperience # failed to identify its superclass
        def contract_type: -> untyped
        def department: -> untyped
        def description: -> untyped
        def employer: -> untyped
        def end_month: -> untyped
        def end_year: -> untyped
        def role: -> untyped
        def start_month: -> untyped
        def start_year: -> untyped
        def initialize: (untyped, untyped) -> untyped
        def printable_values: -> Hash[untyped, untyped]
        def table_printable_values: -> Hash[untyped, untyped]
        def to_table_line: -> String
        def to_s: -> String
      end
    end
  end
end
