# TypeProf 0.30.1

# lib/mindee/errors/mindee_error.rb
module Mindee
  module Errors
    class Errors::MindeeError < StandardError
    end
    class Errors::MindeeAPIError < Errors::MindeeError
    end
    class Errors::MindeeConfigurationError < Errors::MindeeError
    end
    class Errors::MindeeGeometryError < Errors::MindeeError
    end
  end
end
