# lib/mindee/errors/mindee_http_error_v2.rb
module Mindee
  module Errors
    # API V2 HttpError
    class MindeeHTTPErrorV2 < MindeeError
      attr_reader detail: String
      attr_reader status: Integer
      attr_reader code: String
      attr_reader title: String
      attr_reader errors: Array[Parsing::V2::ErrorItem]

      def initialize: (Hash[String, untyped] | Parsing::V2::ErrorResponse) -> void
    end
  end
end
