# lib/mindee/errors/mindee_input_error.rb
module Mindee
  module Errors
    class MindeeInputError < MindeeError
    end
    class MindeeSourceError < MindeeInputError
    end
    class MindeeMimeTypeError < MindeeSourceError
      attr_reader invalid_mimetype: String

      def initialize: (String) -> void
    end
    class MindeeImageError < MindeeInputError
    end
    class MindeePDFError < MindeeInputError
    end
  end
end
