# lib/mindee/errors/mindee_http_error.rb
module Mindee
  module Errors
    class MindeeHTTPError < Errors::MindeeError
      attr_reader api_code: Integer
      attr_reader api_details: String
      attr_reader api_message: String
      attr_reader status_code: Integer

      def initialize: (Hash[String | Symbol, untyped], String, Integer) -> void
    end
    class MindeeHTTPClientError < MindeeHTTPError
    end
    class MindeeHTTPServerError < MindeeHTTPError
    end
  end
end
