# lib/mindee/input/base_parameters.rb

module Mindee
  module Input
    class BaseParameters
      self.@_slug: String

      def self.from_hash: (params: Hash[String | Symbol, untyped]) -> instance
      def self.load_from_hash: (params: Hash[String | Symbol, untyped]) -> Hash[String | Symbol, untyped]

      def _slug: -> String

      attr_reader model_id: String
      attr_reader file_alias: String?
      attr_reader webhook_ids: Array[String]?
      attr_reader polling_options: PollingOptions
      attr_reader close_file: bool
      self.@slug: String

      def initialize: (
          String,
          ?file_alias: String?,
          ?webhook_ids: Array[String]?,
          ?polling_options: Hash[Symbol | String, untyped] | PollingOptions?,
          ?close_file: bool?
        ) -> void

      def append_form_data: (Array[Array[untyped]]) -> Array[Array[untyped]]

      def validate_async_params: () -> void

      private

      def get_clean_polling_options: (Hash[String | Symbol, untyped] | PollingOptions?) -> PollingOptions
    end
  end
end
