module Mindee
  module Input
    class DataSchemaField
      attr_reader title: String
      attr_reader name: String
      attr_reader is_array: bool
      attr_reader type: String
      attr_reader classification_values: String|nil
      attr_reader unique_values: bool|nil
      attr_reader description: String|nil
      attr_reader guidelines: String|nil
      attr_reader nested_fields: Array[Hash[String|Symbol, untyped]]|nil

      def initialize: (Hash[Symbol, untyped]) -> void
      def to_hash: () -> Hash[Symbol, untyped]
      def to_string: () -> String
    end

    class DataSchemaReplace
      attr_reader fields: Array[DataSchemaField]
      def initialize: (Hash[Symbol, untyped]) -> void
      def to_hash: () -> Hash[Symbol, untyped]
      def to_string: () -> String
    end

    class DataSchema
      attr_reader replace: DataSchemaReplace

      def initialize: (Hash[String|Symbol, untyped]|String|DataSchema) -> void
      def to_hash: () -> Hash[Symbol, untyped]
      def to_s: -> String
    end
  end
end
