# lib/mindee/input/local_response.rb
module Mindee
  module Input
    class LocalResponse
      def file: -> StringIO
      def initialize: (File | IO | StringIO | String | Pathname) -> void
      def as_hash: -> Hash[String | Symbol, untyped]
      def self.process_secret_key: (String) -> String
      def get_hmac_signature: (String) -> String
      def valid_hmac_signature?: (String, String) -> bool
      def deserialize_response: (singleton(Parsing::V2::JobResponse) | singleton(Parsing::V2::InferenceResponse))-> (Parsing::V2::JobResponse | Parsing::V2::InferenceResponse)
    end
  end
end
