# lib/mindee/input/local_response.rb
module Mindee
  module Input
    class LocalResponse
      def file: -> StringIO
      def initialize: (untyped) -> Integer
      def as_hash: -> nil
      def self.process_secret_key: (untyped) -> untyped
      def get_hmac_signature: (untyped) -> untyped
      def valid_hmac_signature?: (untyped, untyped) -> untyped
    end
  end
end
