# lib/mindee/input/local_response.rb
module Mindee
  module Input
    class LocalResponse
      attr_reader file: StringIO
      def initialize: (File | IO | StringIO | String | Pathname | Tempfile) -> void
      def as_hash: -> Hash[String | Symbol, untyped]
      def self.process_secret_key: (String) -> String
      def get_hmac_signature: (String) -> String
      def valid_hmac_signature?: (String, String) -> bool
      def deserialize_response: (singleton(V2::Parsing::CommonResponse))-> (V2::Parsing::CommonResponse)
    end
  end
end
