#
# Run static code analysis.
#
name: Static Analysis

on:
  workflow_call:
  workflow_dispatch:

jobs:
  linting:
    name: Run Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.0.0"
        bundler-cache: true

    - name: Analyse the code with Rubocop
      run: |
        bundle exec rubocop ./

    - name: Attempt to generate the documentation
      run: |
        bundle exec rake doc

    - name: Check types using Steep
      run: |
        bundle exec steep check
