#
# Run static code analysis.
#
name: Static Analysis

on:
  workflow_call:
  workflow_dispatch:

jobs:
  linting:
    name: Run Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2.0"
        bundler-cache: true

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

    - name: Analyse the code with Rubocop
      run: |
        bundle install
        bundle exec overcommit --install
        bundle exec overcommit --sign
        bundle exec overcommit --sign pre-commit
        SKIP=Gitleaks bundle exec overcommit --run
