#
# Run integration tests.
#
name: Integration Tests - Minimal Dependencies

on:
  workflow_call:
  workflow_dispatch:

env:
  MINDEE_API_KEY: ${{ secrets.MINDEE_API_KEY_SE_TESTS }}
  WORKFLOW_ID: ${{ secrets.WORKFLOW_ID_SE_TESTS }}
  MINDEE_V2_API_KEY: ${{ secrets.MINDEE_V2_SE_TESTS_API_KEY }}
  MINDEE_V2_FINDOC_MODEL_ID: ${{ secrets.MINDEE_V2_SE_TESTS_FINDOC_MODEL_ID }}
  MINDEE_V2_SE_TESTS_BLANK_PDF_URL: ${{ secrets.MINDEE_V2_SE_TESTS_BLANK_PDF_URL }}
  MINDEE_V2_SE_TESTS_FINDOC_MODEL_ID: ${{ secrets.MINDEE_V2_SE_TESTS_FINDOC_MODEL_ID }}
  MINDEE_V2_SE_TESTS_CLASSIFICATION_MODEL_ID: ${{ secrets.MINDEE_V2_SE_TESTS_CLASSIFICATION_MODEL_ID }}
  MINDEE_V2_SE_TESTS_CROP_MODEL_ID: ${{ secrets.MINDEE_V2_SE_TESTS_CROP_MODEL_ID }}
  MINDEE_V2_SE_TESTS_OCR_MODEL_ID: ${{ secrets.MINDEE_V2_SE_TESTS_OCR_MODEL_ID }}
  MINDEE_V2_SE_TESTS_SPLIT_MODEL_ID: ${{ secrets.MINDEE_V2_SE_TESTS_SPLIT_MODEL_ID }}
  MINDEE_LOG_LEVEL: DEBUG
  MINDEE_GEM_NAME: mindee-lite

jobs:
  integration-tests:
    name: Run Integration Tests
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os:
          - "ubuntu-24.04"
          - "macos-latest"
        ruby:
          - "4.0"
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run Rspec for integration tests
        run: |
          bundle exec rake integration
