name: Crontab

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  test-smoke:
    uses: mindee/mindee-api-ruby/.github/workflows/_test-smoke.yml@main
    secrets: inherit
  test-cli:
    uses: mindee/mindee-api-ruby/.github/workflows/_test-cli.yml@main
    secrets: inherit
