#
# Run static code analysis.
#
name: Static Analysis

on:
  - push

jobs:
  linting:
    name: Run Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
        bundler-cache: true

    - name: Analyse the code with Rubocop
      run: |
        bundle exec rubocop ./
