#
# Run static code analysis.
#
name: Static Analysis

on:
  - push

jobs:
  linting:
    name: Run Static Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7"]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install dependencies
      run: |
        bundle install

    - name: Analyse the code with Rubocop
      run: |
        bundle exec rubocop ./
