name: Pull Request

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  static-analysis:
    uses: ./.github/workflows/_static-analysis.yml
  test-unit:
    uses: ./.github/workflows/_test-units.yml
    needs: static-analysis
    secrets: inherit
  test-unit-lite:
    uses: ./.github/workflows/_test-units.yml
    needs: static-analysis
    secrets: inherit
  test-integration:
    uses: ./.github/workflows/_test-integration.yml
    needs: test-unit
    secrets: inherit
  test-integration-lite:
    uses: ./.github/workflows/_test-integration-lite.yml
    needs: test-unit-lite
    secrets: inherit
  test-smoke:
    uses: ./.github/workflows/_test-smoke.yml
    needs: test-unit
    secrets: inherit
  test-cli:
    uses: ./.github/workflows/_test-cli.yml
    needs: test-unit
    secrets: inherit
