name: Pull Request

on:
  pull_request:

jobs:
  static_analysis:
    uses: mindee/mindee-api-ruby/.github/workflows/_static-analysis.yml@harmonize-CI
  test_units:
    uses: mindee/mindee-api-ruby/.github/workflows/_test-units.yml@harmonize-CI
    needs: static_analysis
    secrets: inherit
  test_regressions:
    uses: mindee/mindee-api-ruby/.github/workflows/_test-regressions.yml@harmonize-CI
    needs: test_units
    secrets: inherit
  test_integrations:
    uses: mindee/mindee-api-ruby/.github/workflows/_test-integrations.yml@harmonize-CI
    needs: test_units
    secrets: inherit
  test_code_samples:
    uses: mindee/mindee-api-ruby/.github/workflows/_test-code-samples.yml@harmonize-CI
    needs: test_units
    secrets: inherit
