name: Push Main Branch

on:
  push:
    branches:
      - main

jobs:
  static_analysis:
    uses: mindee/mindee-api-ruby/.github/workflows/_static-analysis.yml@harmonize-CI
  test_units:
    uses: mindee/mindee-api-ruby/.github/workflows/_test-units.yml@harmonize-CI
    needs: static_analysis
    secrets: inherit
  tag:
    uses: mindee/client-lib-actions/.github/workflows/tag-version.yml@harmonize-CI
    needs: test_units
