#
# Run unit tests.
#
name: Tests

on:
  - push

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - "2.6"
          - "2.7"
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: set up Ruby ${{ matrix.python-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install dependencies
      run: |
        bundle install

    - name: Run Rspec
      run: |
        bundle exec rspec ./spec/*
