#
# Run unit tests.
#
name: Tests

on:
  - push

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "2.6"
          - "2.7"
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run Rspec
      run: |
        bundle exec rspec ./spec/*
